npmName: revengai
licenseName: MIT
gitUserId: RevEngAI
gitRepoId: sdk-typescript
projectName: "@revengai/sdk"
additionalProperties:
  apiDocPath: docs/
# When an unknown enum value is found map to unknown_default_open_api
enumUnknownDefaultCase: true
