/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AddCalleeInputBody {
    /**
    * Internal callee function ID; 0 means not provided
    */
    'calleeFunctionId'?: number;
    /**
    * Callee name (for external calls)
    */
    'calleeName'?: string;
    /**
    * Virtual address of the callee
    */
    'calleeVaddr': number;
    /**
    * Whether the callee is outside the binary
    */
    'isExternal': boolean;
    /**
    * Thunked virtual address
    */
    'thunkedVaddr'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "calleeFunctionId",
            "baseName": "callee_function_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "calleeName",
            "baseName": "callee_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "calleeVaddr",
            "baseName": "callee_vaddr",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "isExternal",
            "baseName": "is_external",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "thunkedVaddr",
            "baseName": "thunked_vaddr",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return AddCalleeInputBody.attributeTypeMap;
    }

    public constructor() {
    }
}
