/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AnalysisAccessInfo } from '../models/AnalysisAccessInfo';
import { HttpFile } from '../http/http';

export class AnalysisDetailResponse {
    'access': AnalysisAccessInfo;
    'analysisId': number;
    'analysisScope': string;
    'architecture': string;
    'binaryDynamic': boolean;
    'binaryFormat': string;
    'binaryName': string;
    'binarySize': number;
    'binaryType': string;
    'creation': string;
    'debug': boolean;
    'modelName': string;
    'sbom'?: { [key: string]: any; } | null;
    'sha256Hash': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "access",
            "baseName": "access",
            "type": "AnalysisAccessInfo",
            "format": ""
        },
        {
            "name": "analysisId",
            "baseName": "analysis_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "analysisScope",
            "baseName": "analysis_scope",
            "type": "string",
            "format": ""
        },
        {
            "name": "architecture",
            "baseName": "architecture",
            "type": "string",
            "format": ""
        },
        {
            "name": "binaryDynamic",
            "baseName": "binary_dynamic",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "binaryFormat",
            "baseName": "binary_format",
            "type": "string",
            "format": ""
        },
        {
            "name": "binaryName",
            "baseName": "binary_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "binarySize",
            "baseName": "binary_size",
            "type": "number",
            "format": ""
        },
        {
            "name": "binaryType",
            "baseName": "binary_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "creation",
            "baseName": "creation",
            "type": "string",
            "format": ""
        },
        {
            "name": "debug",
            "baseName": "debug",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "modelName",
            "baseName": "model_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "sbom",
            "baseName": "sbom",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "sha256Hash",
            "baseName": "sha_256_hash",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AnalysisDetailResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
