/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AnalysisScope } from '../models/AnalysisScope';
import { HttpFile } from '../http/http';

export class AnalysisUpdateRequest {
    'binaryName'?: string | null;
    'analysisScope'?: AnalysisScope | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "binaryName",
            "baseName": "binary_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "analysisScope",
            "baseName": "analysis_scope",
            "type": "AnalysisScope",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AnalysisUpdateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


