/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BinariesTaskStatus } from '../models/BinariesTaskStatus';
import { HttpFile } from '../http/http';

export class AnalysisStringsStatusResponse {
    /**
    * The current status of the strings extraction task
    */
    'status': BinariesTaskStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "BinariesTaskStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AnalysisStringsStatusResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


