/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SandboxOptions } from '../models/SandboxOptions';
import { ScrapeThirdPartyConfig } from '../models/ScrapeThirdPartyConfig';
import { HttpFile } from '../http/http';

export class AnalysisConfig {
    /**
    * Settings to scrape third party sources
    */
    'scrapeThirdPartyConfig'?: ScrapeThirdPartyConfig;
    /**
    * A configuration option for fetching CVEs data.
    */
    'generateCves'?: boolean;
    /**
    * A configuration option for generating software bill of materials data.
    */
    'generateSbom'?: boolean;
    /**
    * A configuration option for generating capabilities of a binary
    */
    'generateCapabilities'?: boolean;
    /**
    * When enabled, skips using cached data within the processing.
    */
    'noCache'?: boolean;
    /**
    * Enables an advanced security analysis.
    */
    'advancedAnalysis'?: boolean;
    /**
    * Including a sandbox config enables the dynamic execution sandbox
    */
    'sandboxConfig'?: SandboxOptions;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "scrapeThirdPartyConfig",
            "baseName": "scrape_third_party_config",
            "type": "ScrapeThirdPartyConfig",
            "format": ""
        },
        {
            "name": "generateCves",
            "baseName": "generate_cves",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "generateSbom",
            "baseName": "generate_sbom",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "generateCapabilities",
            "baseName": "generate_capabilities",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "noCache",
            "baseName": "no_cache",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "advancedAnalysis",
            "baseName": "advanced_analysis",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sandboxConfig",
            "baseName": "sandbox_config",
            "type": "SandboxOptions",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AnalysisConfig.attributeTypeMap;
    }

    public constructor() {
    }
}
