/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AnalysisCreateResponse {
    /**
    * ID of created analysis
    */
    'analysisId': number;
    /**
    * ID of created binary
    */
    'binaryId': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "analysisId",
            "baseName": "analysis_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "binaryId",
            "baseName": "binary_id",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AnalysisCreateResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
