/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FileActivityEntry } from '../models/FileActivityEntry';
import { ModuleLoadEntry } from '../models/ModuleLoadEntry';
import { MutexEntry } from '../models/MutexEntry';
import { NetworkActivity } from '../models/NetworkActivity';
import { ProcessActivityEntry } from '../models/ProcessActivityEntry';
import { ProcessExtractedFiles } from '../models/ProcessExtractedFiles';
import { ProcessMemdumps } from '../models/ProcessMemdumps';
import { ProcessTree } from '../models/ProcessTree';
import { RegistryOperation } from '../models/RegistryOperation';
import { ReportInfo } from '../models/ReportInfo';
import { ScheduledTaskEntry } from '../models/ScheduledTaskEntry';
import { ServiceEntry } from '../models/ServiceEntry';
import { StartupInfo } from '../models/StartupInfo';
import { Ttp } from '../models/Ttp';
import { HttpFile } from '../http/http';

export class AnalysisReport {
    'extractedFiles'?: Array<ProcessExtractedFiles> | null;
    'fileActivity'?: Array<FileActivityEntry> | null;
    'info': ReportInfo;
    'memdumps'?: Array<ProcessMemdumps> | null;
    'moduleLoadAddresses'?: Array<ModuleLoadEntry> | null;
    'mutexes'?: Array<MutexEntry> | null;
    'networkActivity'?: NetworkActivity;
    'processActivity'?: Array<ProcessActivityEntry> | null;
    'processTree'?: ProcessTree;
    'registryOperations'?: Array<RegistryOperation> | null;
    'scheduledTasks'?: Array<ScheduledTaskEntry> | null;
    'services'?: Array<ServiceEntry> | null;
    'startup'?: StartupInfo;
    'threatScore': number;
    'ttps'?: Array<Ttp> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "extractedFiles",
            "baseName": "extracted_files",
            "type": "Array<ProcessExtractedFiles>",
            "format": ""
        },
        {
            "name": "fileActivity",
            "baseName": "file_activity",
            "type": "Array<FileActivityEntry>",
            "format": ""
        },
        {
            "name": "info",
            "baseName": "info",
            "type": "ReportInfo",
            "format": ""
        },
        {
            "name": "memdumps",
            "baseName": "memdumps",
            "type": "Array<ProcessMemdumps>",
            "format": ""
        },
        {
            "name": "moduleLoadAddresses",
            "baseName": "module_load_addresses",
            "type": "Array<ModuleLoadEntry>",
            "format": ""
        },
        {
            "name": "mutexes",
            "baseName": "mutexes",
            "type": "Array<MutexEntry>",
            "format": ""
        },
        {
            "name": "networkActivity",
            "baseName": "network_activity",
            "type": "NetworkActivity",
            "format": ""
        },
        {
            "name": "processActivity",
            "baseName": "process_activity",
            "type": "Array<ProcessActivityEntry>",
            "format": ""
        },
        {
            "name": "processTree",
            "baseName": "process_tree",
            "type": "ProcessTree",
            "format": ""
        },
        {
            "name": "registryOperations",
            "baseName": "registry_operations",
            "type": "Array<RegistryOperation>",
            "format": ""
        },
        {
            "name": "scheduledTasks",
            "baseName": "scheduled_tasks",
            "type": "Array<ScheduledTaskEntry>",
            "format": ""
        },
        {
            "name": "services",
            "baseName": "services",
            "type": "Array<ServiceEntry>",
            "format": ""
        },
        {
            "name": "startup",
            "baseName": "startup",
            "type": "StartupInfo",
            "format": ""
        },
        {
            "name": "threatScore",
            "baseName": "threat_score",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "ttps",
            "baseName": "ttps",
            "type": "Array<Ttp>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AnalysisReport.attributeTypeMap;
    }

    public constructor() {
    }
}
