/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AnalysisConfig } from '../models/AnalysisConfig';
import { AnalysisScope } from '../models/AnalysisScope';
import { AutoRunAgents } from '../models/AutoRunAgents';
import { BinaryConfig } from '../models/BinaryConfig';
import { Symbols } from '../models/Symbols';
import { Tag } from '../models/Tag';
import { HttpFile } from '../http/http';

export class AnalysisCreateRequest {
    /**
    * The name of the file
    */
    'filename': string;
    /**
    * The sha256 hash of the file
    */
    'sha256Hash': string;
    /**
    * List of tags to assign to an analysis
    */
    'tags'?: Array<Tag>;
    /**
    * The scope of the analysis determines who can access it
    */
    'analysisScope'?: AnalysisScope;
    'symbols'?: Symbols | null;
    'debugHash'?: string | null;
    /**
    * The analysis config enables the configuration of optional analysis stages
    */
    'analysisConfig'?: AnalysisConfig;
    /**
    * The binary config can override automatically determined values such as ISA, Platform, File Format, etc
    */
    'binaryConfig'?: BinaryConfig;
    'autoRunAgents'?: AutoRunAgents;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string",
            "format": ""
        },
        {
            "name": "sha256Hash",
            "baseName": "sha_256_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<Tag>",
            "format": ""
        },
        {
            "name": "analysisScope",
            "baseName": "analysis_scope",
            "type": "AnalysisScope",
            "format": ""
        },
        {
            "name": "symbols",
            "baseName": "symbols",
            "type": "Symbols",
            "format": ""
        },
        {
            "name": "debugHash",
            "baseName": "debug_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "analysisConfig",
            "baseName": "analysis_config",
            "type": "AnalysisConfig",
            "format": ""
        },
        {
            "name": "binaryConfig",
            "baseName": "binary_config",
            "type": "BinaryConfig",
            "format": ""
        },
        {
            "name": "autoRunAgents",
            "baseName": "auto_run_agents",
            "type": "AutoRunAgents",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AnalysisCreateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


