/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AnalysisBasicInfoOutputBody {
    /**
    * PUBLIC, PRIVATE, or TEAM
    */
    'analysisScope': AnalysisBasicInfoOutputBodyAnalysisScopeEnum;
    /**
    * Base address of the binary, null when unknown
    */
    'baseAddress': number | null;
    /**
    * Binary ID
    */
    'binaryId': number;
    /**
    * Binary filename
    */
    'binaryName': string;
    /**
    * Binary size in bytes
    */
    'binarySize': number;
    /**
    * UUID of the binary, omitted when not set
    */
    'binaryUuid': string;
    /**
    * When the binary was uploaded
    */
    'creation': Date;
    /**
    * True when the binary was analysed with debug symbols
    */
    'debug': boolean;
    /**
    * Detected instruction-set architecture; empty when unavailable
    */
    'detectedArchitecture': string;
    /**
    * Detected binary container format; empty when unavailable
    */
    'detectedBinaryFormat': string;
    /**
    * Detected operating-system platform; empty when unavailable
    */
    'detectedBinaryType': string;
    /**
    * Number of functions in the binary
    */
    'functionCount': number;
    /**
    * True when the analysis was run in advanced mode
    */
    'isAdvanced': boolean;
    /**
    * True when the caller is the analysis owner
    */
    'isOwner': boolean;
    /**
    * True when the analysis is owned by a system user
    */
    'isSystem': boolean;
    /**
    * Model ID
    */
    'modelId': number;
    /**
    * Model used for analysis
    */
    'modelName': string;
    /**
    * True when the analysis ran on a model older than the current one, so its owner can re-analyse it on the latest. Describes the analysis, not the caller\'s rights — only the owner may act on it
    */
    'modelUpgradeAvailable': boolean;
    /**
    * Username of the analysis owner
    */
    'ownerUsername': string;
    /**
    * Sequencer version, omitted when not set
    */
    'sequencerVersion'?: string;
    /**
    * SHA-256 hash of the binary
    */
    'sha256Hash': string;
    /**
    * User-supplied instruction-set architecture; \"AUTO\" when not overridden
    */
    'suppliedArchitecture': string;
    /**
    * User-supplied binary container format; \"AUTO\" when not overridden
    */
    'suppliedBinaryFormat': string;
    /**
    * User-supplied operating-system platform; \"AUTO\" when not overridden
    */
    'suppliedBinaryType': string;
    /**
    * Team ID of the analysis
    */
    'teamId': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "analysisScope",
            "baseName": "analysis_scope",
            "type": "AnalysisBasicInfoOutputBodyAnalysisScopeEnum",
            "format": ""
        },
        {
            "name": "baseAddress",
            "baseName": "base_address",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "binaryId",
            "baseName": "binary_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "binaryName",
            "baseName": "binary_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "binarySize",
            "baseName": "binary_size",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "binaryUuid",
            "baseName": "binary_uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "creation",
            "baseName": "creation",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "debug",
            "baseName": "debug",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "detectedArchitecture",
            "baseName": "detected_architecture",
            "type": "string",
            "format": ""
        },
        {
            "name": "detectedBinaryFormat",
            "baseName": "detected_binary_format",
            "type": "string",
            "format": ""
        },
        {
            "name": "detectedBinaryType",
            "baseName": "detected_binary_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "functionCount",
            "baseName": "function_count",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "isAdvanced",
            "baseName": "is_advanced",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isOwner",
            "baseName": "is_owner",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isSystem",
            "baseName": "is_system",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "modelId",
            "baseName": "model_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "modelName",
            "baseName": "model_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "modelUpgradeAvailable",
            "baseName": "model_upgrade_available",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "ownerUsername",
            "baseName": "owner_username",
            "type": "string",
            "format": ""
        },
        {
            "name": "sequencerVersion",
            "baseName": "sequencer_version",
            "type": "string",
            "format": ""
        },
        {
            "name": "sha256Hash",
            "baseName": "sha_256_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "suppliedArchitecture",
            "baseName": "supplied_architecture",
            "type": "string",
            "format": ""
        },
        {
            "name": "suppliedBinaryFormat",
            "baseName": "supplied_binary_format",
            "type": "string",
            "format": ""
        },
        {
            "name": "suppliedBinaryType",
            "baseName": "supplied_binary_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "teamId",
            "baseName": "team_id",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return AnalysisBasicInfoOutputBody.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AnalysisBasicInfoOutputBodyAnalysisScopeEnum {
    Private = 'PRIVATE',
    Public = 'PUBLIC',
    Team = 'TEAM',
    UnknownDefaultOpenApi = '11184809'
}

