/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AnalysisTagBody } from '../models/AnalysisTagBody';
import { HttpFile } from '../http/http';

export class AnalysisRecordBody {
    /**
    * Analysis ID
    */
    'analysisId': number;
    /**
    * Scope of the analysis
    */
    'analysisScope': AnalysisRecordBodyAnalysisScopeEnum;
    /**
    * Binary base address
    */
    'baseAddress': number;
    /**
    * Binary ID
    */
    'binaryId': number;
    /**
    * Binary filename
    */
    'binaryName': string;
    /**
    * Binary size in bytes
    */
    'binarySize': number;
    /**
    * When the analysis was created
    */
    'creation': Date;
    /**
    * Hash of the binary\'s provided function boundaries
    */
    'functionBoundariesHash': string;
    /**
    * True when the caller owns the analysis
    */
    'isOwner': boolean;
    /**
    * Model ID
    */
    'modelId': number;
    /**
    * Model name
    */
    'modelName': string;
    /**
    * SHA-256 hash of the binary
    */
    'sha256Hash': string;
    /**
    * Analysis status
    */
    'status': string;
    /**
    * Tags associated with the binary
    */
    'tags': Array<AnalysisTagBody> | null;
    /**
    * Username of the analysis owner
    */
    'username': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "analysisId",
            "baseName": "analysis_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "analysisScope",
            "baseName": "analysis_scope",
            "type": "AnalysisRecordBodyAnalysisScopeEnum",
            "format": ""
        },
        {
            "name": "baseAddress",
            "baseName": "base_address",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "binaryId",
            "baseName": "binary_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "binaryName",
            "baseName": "binary_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "binarySize",
            "baseName": "binary_size",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "creation",
            "baseName": "creation",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "functionBoundariesHash",
            "baseName": "function_boundaries_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "isOwner",
            "baseName": "is_owner",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "modelId",
            "baseName": "model_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "modelName",
            "baseName": "model_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "sha256Hash",
            "baseName": "sha_256_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<AnalysisTagBody>",
            "format": ""
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AnalysisRecordBody.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AnalysisRecordBodyAnalysisScopeEnum {
    Public = 'PUBLIC',
    Private = 'PRIVATE',
    Team = 'TEAM',
    UnknownDefaultOpenApi = '11184809'
}

