/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AnalysisUpdateRequest {
    'binaryName'?: string | null;
    'analysisScope'?: AnalysisUpdateRequestAnalysisScopeEnum | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "binaryName",
            "baseName": "binary_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "analysisScope",
            "baseName": "analysis_scope",
            "type": "AnalysisUpdateRequestAnalysisScopeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AnalysisUpdateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AnalysisUpdateRequestAnalysisScopeEnum {
    Public = 'PUBLIC',
    Private = 'PRIVATE'
}

