/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppApiRestV2FunctionsTypesFunction } from '../models/AppApiRestV2FunctionsTypesFunction';
import { HttpFile } from '../http/http';

export class AnalysisFunctions {
    /**
    * The functions associated with the analysis
    */
    'functions': Array<AppApiRestV2FunctionsTypesFunction>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "functions",
            "baseName": "functions",
            "type": "Array<AppApiRestV2FunctionsTypesFunction>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AnalysisFunctions.attributeTypeMap;
    }

    public constructor() {
    }
}
