/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppApiRestV2AnalysesEnumsDynamicExecutionStatus } from '../models/AppApiRestV2AnalysesEnumsDynamicExecutionStatus';
import { TagItem } from '../models/TagItem';
import { HttpFile } from '../http/http';

export class AnalysisRecord {
    /**
    * ID to identify analysis
    */
    'analysisId': number;
    /**
    * Scope of the analysis
    */
    'analysisScope': string;
    /**
    * The base address of the binary
    */
    'baseAddress': number;
    /**
    * ID to identify the binary analyse
    */
    'binaryId': number;
    /**
    * The name of the file uploaded
    */
    'binaryName': string;
    /**
    * The size of the binary
    */
    'binarySize': number;
    /**
    * The datetime of when the analysis was created
    */
    'creation': Date;
    'dynamicExecutionStatus'?: AppApiRestV2AnalysesEnumsDynamicExecutionStatus | null;
    'dynamicExecutionTaskId'?: number | null;
    /**
    * The hash of the function boundaries
    */
    'functionBoundariesHash': string;
    /**
    * Whether the current user is the owner of a binary
    */
    'isOwner': boolean;
    /**
    * ID to identify the model used for analysis
    */
    'modelId': number;
    /**
    * Name of the model used for analysis
    */
    'modelName': string;
    /**
    * The hash of the binary
    */
    'sha256Hash': string;
    /**
    * The current status of analysis
    */
    'status': string;
    /**
    * List of tags associated with the analysis
    */
    'tags'?: Array<TagItem>;
    /**
    * The username of the analysis owner
    */
    'username': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "analysisId",
            "baseName": "analysis_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "analysisScope",
            "baseName": "analysis_scope",
            "type": "string",
            "format": ""
        },
        {
            "name": "baseAddress",
            "baseName": "base_address",
            "type": "number",
            "format": "bigint"
        },
        {
            "name": "binaryId",
            "baseName": "binary_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "binaryName",
            "baseName": "binary_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "binarySize",
            "baseName": "binary_size",
            "type": "number",
            "format": ""
        },
        {
            "name": "creation",
            "baseName": "creation",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dynamicExecutionStatus",
            "baseName": "dynamic_execution_status",
            "type": "AppApiRestV2AnalysesEnumsDynamicExecutionStatus",
            "format": ""
        },
        {
            "name": "dynamicExecutionTaskId",
            "baseName": "dynamic_execution_task_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "functionBoundariesHash",
            "baseName": "function_boundaries_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "isOwner",
            "baseName": "is_owner",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "modelId",
            "baseName": "model_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "modelName",
            "baseName": "model_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "sha256Hash",
            "baseName": "sha_256_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<TagItem>",
            "format": ""
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AnalysisRecord.attributeTypeMap;
    }

    public constructor() {
    }
}


