/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SearchBinaryIds } from '../models/SearchBinaryIds';
import { SearchFunctionIds } from '../models/SearchFunctionIds';
import { HttpFile } from '../http/http';

export class ANNFunction {
    /**
    * The amount of neighbours per function ID
    */
    'limit'?: number;
    /**
    * The distance between two neighbours
    */
    'distance'?: number;
    /**
    * Perform a search on functions within a list of analyses
    */
    'analysisSearchIds'?: Array<number | null>;
    /**
    * Search only within these collections
    */
    'collectionSearchIds'?: Array<number | null>;
    'searchBinaryIds'?: SearchBinaryIds;
    'searchFunctionIds'?: SearchFunctionIds;
    /**
    * Searches for only functions which are debug
    */
    'debugOnly'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "distance",
            "baseName": "distance",
            "type": "number",
            "format": ""
        },
        {
            "name": "analysisSearchIds",
            "baseName": "analysis_search_ids",
            "type": "Array<number | null>",
            "format": ""
        },
        {
            "name": "collectionSearchIds",
            "baseName": "collection_search_ids",
            "type": "Array<number | null>",
            "format": ""
        },
        {
            "name": "searchBinaryIds",
            "baseName": "search_binary_ids",
            "type": "SearchBinaryIds",
            "format": ""
        },
        {
            "name": "searchFunctionIds",
            "baseName": "search_function_ids",
            "type": "SearchFunctionIds",
            "format": ""
        },
        {
            "name": "debugOnly",
            "baseName": "debug_only",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ANNFunction.attributeTypeMap;
    }

    public constructor() {
    }
}
