/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EvidenceEffect } from '../models/EvidenceEffect';
import { ImportedApi } from '../models/ImportedApi';
import { HttpFile } from '../http/http';

/**
* A known combination of APIs without a demonstrated semantic flow.
*/
export class ApiCombinationEvidence {
    'evidenceKind'?: ApiCombinationEvidenceEvidenceKindEnum;
    'kind'?: ApiCombinationEvidenceKindEnum;
    'effect': EvidenceEffect;
    'strength'?: ApiCombinationEvidenceStrengthEnum;
    'apis': Array<ImportedApi>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "evidenceKind",
            "baseName": "evidence_kind",
            "type": "ApiCombinationEvidenceEvidenceKindEnum",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "ApiCombinationEvidenceKindEnum",
            "format": ""
        },
        {
            "name": "effect",
            "baseName": "effect",
            "type": "EvidenceEffect",
            "format": ""
        },
        {
            "name": "strength",
            "baseName": "strength",
            "type": "ApiCombinationEvidenceStrengthEnum",
            "format": ""
        },
        {
            "name": "apis",
            "baseName": "apis",
            "type": "Array<ImportedApi>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiCombinationEvidence.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ApiCombinationEvidenceEvidenceKindEnum {
    ApiCombination = 'api_combination',
    UnknownDefaultOpenApi = '11184809'
}
export enum ApiCombinationEvidenceKindEnum {
    DeterministicDerivation = 'deterministic_derivation',
    UnknownDefaultOpenApi = '11184809'
}
export enum ApiCombinationEvidenceStrengthEnum {
    Indirect = 'indirect',
    UnknownDefaultOpenApi = '11184809'
}

