/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ErrorBody } from '../models/ErrorBody';
import { HttpFile } from '../http/http';

export class APIError {
    /**
    * A URL to the JSON Schema for this object.
    */
    'schema'?: string;
    'error': ErrorBody;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "schema",
            "baseName": "$schema",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "ErrorBody",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return APIError.attributeTypeMap;
    }

    public constructor() {
    }
}
