/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AutoUnstripRequest {
    /**
    * Whether to apply the matched function names to the target binary, default is False
    * @deprecated
    */
    'apply'?: boolean;
    /**
    * Confidence threshold for applying function names as a percentage, default is 90
    * @deprecated
    */
    'confidenceThreshold'?: number;
    /**
    * Minimum number of matching functions required to consider for a match, default is 10
    * @deprecated
    */
    'minGroupSize'?: number;
    /**
    * Minimum similarity expected for a match as a percentage, default is 90
    * @deprecated
    */
    'minSimilarity'?: number;
    /**
    * If set to true, forces the system to bypass any cached results and perform a fresh computation
    * @deprecated
    */
    'noCache'?: boolean;
    /**
    * If set to true, only returns the status of the auto-unstrip operation without the actual results
    * @deprecated
    */
    'statusOnly'?: boolean;
    /**
    * Whether to use canonical function names during matching for auto-unstrip, default is False
    */
    'useCanonicalNames'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "apply",
            "baseName": "apply",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "confidenceThreshold",
            "baseName": "confidence_threshold",
            "type": "number",
            "format": ""
        },
        {
            "name": "minGroupSize",
            "baseName": "min_group_size",
            "type": "number",
            "format": ""
        },
        {
            "name": "minSimilarity",
            "baseName": "min_similarity",
            "type": "number",
            "format": ""
        },
        {
            "name": "noCache",
            "baseName": "no_cache",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "statusOnly",
            "baseName": "status_only",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "useCanonicalNames",
            "baseName": "use_canonical_names",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AutoUnstripRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
