/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MatchedFunctionSuggestion } from '../models/MatchedFunctionSuggestion';
import { HttpFile } from '../http/http';

export class AutoUnstripResponse {
    'applied'?: boolean | null;
    'errorMessage'?: string | null;
    'matches'?: Array<MatchedFunctionSuggestion> | null;
    /**
    * Progress of the auto-unstrip operation, represented as a percentage
    * @deprecated
    */
    'progress'?: number;
    'status'?: string | null;
    'totalTime'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "applied",
            "baseName": "applied",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "errorMessage",
            "baseName": "error_message",
            "type": "string",
            "format": ""
        },
        {
            "name": "matches",
            "baseName": "matches",
            "type": "Array<MatchedFunctionSuggestion>",
            "format": ""
        },
        {
            "name": "progress",
            "baseName": "progress",
            "type": "number",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalTime",
            "baseName": "total_time",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AutoUnstripResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
