/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ErrorModel } from '../models/ErrorModel';
import { GetAiDecompilationRatingResponse } from '../models/GetAiDecompilationRatingResponse';
import { MetaModel } from '../models/MetaModel';
import { HttpFile } from '../http/http';

export class BaseResponseUnionGetAiDecompilationRatingResponseNoneType {
    /**
    * Response status on whether the request succeeded
    */
    'status'?: boolean;
    'data'?: GetAiDecompilationRatingResponse | null;
    'message'?: string | null;
    'errors'?: Array<ErrorModel> | null;
    /**
    * Metadata
    */
    'meta'?: MetaModel;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "GetAiDecompilationRatingResponse",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<ErrorModel>",
            "format": ""
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "MetaModel",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BaseResponseUnionGetAiDecompilationRatingResponseNoneType.attributeTypeMap;
    }

    public constructor() {
    }
}
