/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Basic {
    /**
    * The name of the binary uploaded
    */
    'binaryName': string;
    /**
    * The size of the binary uploaded (bytes)
    */
    'binarySize': number;
    /**
    * When the binary was uploaded
    */
    'creation': Date;
    /**
    * The hash of the binary uploaded
    */
    'sha256Hash': string;
    /**
    * The model name used for analysis
    */
    'modelName': string;
    /**
    * The model ID used for analysis
    */
    'modelId': number;
    /**
    * The name of the owner of the binary
    */
    'ownerUsername': string;
    /**
    * Whether the analysis is a system analysis
    */
    'isSystem': boolean;
    /**
    * The scope of the analysis
    */
    'analysisScope': string;
    /**
    * Whether the current user is the owner
    */
    'isOwner': boolean;
    /**
    * Whether the current analysis was analysed with debug symbols
    */
    'debug': boolean;
    /**
    * The number of functions in the binary
    */
    'functionCount': number;
    /**
    * Whether the analysis was advanced
    */
    'isAdvanced': boolean;
    'baseAddress': number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "binaryName",
            "baseName": "binary_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "binarySize",
            "baseName": "binary_size",
            "type": "number",
            "format": ""
        },
        {
            "name": "creation",
            "baseName": "creation",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "sha256Hash",
            "baseName": "sha_256_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "modelName",
            "baseName": "model_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "modelId",
            "baseName": "model_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "ownerUsername",
            "baseName": "owner_username",
            "type": "string",
            "format": ""
        },
        {
            "name": "isSystem",
            "baseName": "is_system",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "analysisScope",
            "baseName": "analysis_scope",
            "type": "string",
            "format": ""
        },
        {
            "name": "isOwner",
            "baseName": "is_owner",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "debug",
            "baseName": "debug",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "functionCount",
            "baseName": "function_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "isAdvanced",
            "baseName": "is_advanced",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "baseAddress",
            "baseName": "base_address",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Basic.attributeTypeMap;
    }

    public constructor() {
    }
}
