/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BatchBinaryMatchResult } from '../models/BatchBinaryMatchResult';
import { HttpFile } from '../http/http';

export class BatchMatchingOutputBody {
    /**
    * Per-binary status (order matches the request).
    */
    'perBinary': Array<BatchBinaryMatchResult> | null;
    /**
    * Aggregate status across the batch: COMPLETED when every binary is completed, FAILED if any failed, RUNNING/PENDING otherwise.
    */
    'status': BatchMatchingOutputBodyStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "perBinary",
            "baseName": "per_binary",
            "type": "Array<BatchBinaryMatchResult>",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "BatchMatchingOutputBodyStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BatchMatchingOutputBody.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum BatchMatchingOutputBodyStatusEnum {
    Uninitialised = 'UNINITIALISED',
    Pending = 'PENDING',
    Running = 'RUNNING',
    Completed = 'COMPLETED',
    Failed = 'FAILED',
    UnknownDefaultOpenApi = '11184809'
}

