/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BatchBinaryMatchResult {
    /**
    * Target binary
    */
    'binaryId': number;
    /**
    * Error description when status=FAILED.
    */
    'errorMessage'?: string;
    /**
    * Number of source functions that received at least one candidate match. Only meaningful when status=COMPLETED.
    */
    'matchedFunctionCount': number;
    /**
    * Per-binary workflow status
    */
    'status': BatchBinaryMatchResultStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "binaryId",
            "baseName": "binary_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "errorMessage",
            "baseName": "error_message",
            "type": "string",
            "format": ""
        },
        {
            "name": "matchedFunctionCount",
            "baseName": "matched_function_count",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "BatchBinaryMatchResultStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BatchBinaryMatchResult.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum BatchBinaryMatchResultStatusEnum {
    Uninitialised = 'UNINITIALISED',
    Pending = 'PENDING',
    Running = 'RUNNING',
    Completed = 'COMPLETED',
    Failed = 'FAILED',
    UnknownDefaultOpenApi = '11184809'
}

