/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BatchUpdateDataTypesItem {
    'dataTypes': any | null;
    /**
    * Current stored version. Pass 0 on the first write.
    */
    'dataTypesVersion': number;
    /**
    * Function ID
    */
    'functionId': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dataTypes",
            "baseName": "data_types",
            "type": "any",
            "format": ""
        },
        {
            "name": "dataTypesVersion",
            "baseName": "data_types_version",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "functionId",
            "baseName": "function_id",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return BatchUpdateDataTypesItem.attributeTypeMap;
    }

    public constructor() {
    }
}
