/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BinaryExternalsResponse {
    /**
    * SHA256 hash of the binary
    */
    'sha256Hash': string;
    /**
    * VirusTotal information
    */
    'vt': { [key: string]: any; };
    /**
    * VirusTotal last updated date
    */
    'vtLastUpdated': Date;
    /**
    * MalwareBazaar information
    */
    'mb': { [key: string]: any; };
    /**
    * MalwareBazaar last updated date
    */
    'mbLastUpdated': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sha256Hash",
            "baseName": "sha_256_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "vt",
            "baseName": "vt",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "vtLastUpdated",
            "baseName": "vt_last_updated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "mb",
            "baseName": "mb",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "mbLastUpdated",
            "baseName": "mb_last_updated",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return BinaryExternalsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
