/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BinaryAdditionalDetailsDataResponse } from '../models/BinaryAdditionalDetailsDataResponse';
import { HttpFile } from '../http/http';

export class BinaryAdditionalResponse {
    'binaryId': number;
    'details': BinaryAdditionalDetailsDataResponse | null;
    'creation'?: Date | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "binaryId",
            "baseName": "binary_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "BinaryAdditionalDetailsDataResponse",
            "format": ""
        },
        {
            "name": "creation",
            "baseName": "creation",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return BinaryAdditionalResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
