/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ELFModel } from '../models/ELFModel';
import { FileMetadata } from '../models/FileMetadata';
import { PEModel } from '../models/PEModel';
import { HttpFile } from '../http/http';

export class BinaryAdditionalDetailsDataResponse {
    'file': FileMetadata;
    'pe'?: PEModel | null;
    'elf'?: ELFModel | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "file",
            "baseName": "file",
            "type": "FileMetadata",
            "format": ""
        },
        {
            "name": "pe",
            "baseName": "pe",
            "type": "PEModel",
            "format": ""
        },
        {
            "name": "elf",
            "baseName": "elf",
            "type": "ELFModel",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BinaryAdditionalDetailsDataResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
