/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BulkCreateUserResult } from '../models/BulkCreateUserResult';
import { HttpFile } from '../http/http';

export class BulkCreateUsersOutputBody {
    'failed': number;
    'results': Array<BulkCreateUserResult> | null;
    'succeeded': number;
    'total': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "failed",
            "baseName": "failed",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<BulkCreateUserResult>",
            "format": ""
        },
        {
            "name": "succeeded",
            "baseName": "succeeded",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return BulkCreateUsersOutputBody.attributeTypeMap;
    }

    public constructor() {
    }
}
