/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Display } from '../models/Display';
import { HttpFile } from '../http/http';

/**
* One exact, contiguous sequence of binary bytes.
*/
export class BytesConstant {
    'format'?: BytesConstantFormatEnum;
    /**
    * Hexadecimal byte pairs representing one exact, contiguous binary value.
    */
    'value': string;
    'display'?: Display;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "format",
            "baseName": "format",
            "type": "BytesConstantFormatEnum",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "display",
            "baseName": "display",
            "type": "Display",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BytesConstant.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum BytesConstantFormatEnum {
    Bytes = 'bytes',
    UnknownDefaultOpenApi = '11184809'
}

