/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EvidenceEffect } from '../models/EvidenceEffect';
import { HttpFile } from '../http/http';

/**
* A concrete sequence of calls connecting program locations.
*/
export class CallChainEvidence {
    'evidenceKind'?: CallChainEvidenceEvidenceKindEnum;
    'kind'?: CallChainEvidenceKindEnum;
    'effect': EvidenceEffect;
    'strength'?: CallChainEvidenceStrengthEnum;
    'callChain': Array<number>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "evidenceKind",
            "baseName": "evidence_kind",
            "type": "CallChainEvidenceEvidenceKindEnum",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "CallChainEvidenceKindEnum",
            "format": ""
        },
        {
            "name": "effect",
            "baseName": "effect",
            "type": "EvidenceEffect",
            "format": ""
        },
        {
            "name": "strength",
            "baseName": "strength",
            "type": "CallChainEvidenceStrengthEnum",
            "format": ""
        },
        {
            "name": "callChain",
            "baseName": "call_chain",
            "type": "Array<number>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CallChainEvidence.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CallChainEvidenceEvidenceKindEnum {
    CallChain = 'call_chain',
    UnknownDefaultOpenApi = '11184809'
}
export enum CallChainEvidenceKindEnum {
    DeterministicDerivation = 'deterministic_derivation',
    UnknownDefaultOpenApi = '11184809'
}
export enum CallChainEvidenceStrengthEnum {
    Direct = 'direct',
    UnknownDefaultOpenApi = '11184809'
}

