/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CalleeFunctionInfo {
    /**
    * Name of the called function
    */
    'calleeName': string;
    /**
    * Virtual address of the called function
    */
    'calleeVaddr': string;
    'dashboardUrl': string | null;
    /**
    * Unique identifier of the function
    */
    'functionId': number;
    /**
    * Indicates if the function is external
    */
    'isExternal'?: boolean;
    'matchedFunctionId': number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "calleeName",
            "baseName": "callee_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "calleeVaddr",
            "baseName": "callee_vaddr",
            "type": "string",
            "format": ""
        },
        {
            "name": "dashboardUrl",
            "baseName": "dashboard_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "functionId",
            "baseName": "function_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "isExternal",
            "baseName": "is_external",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "matchedFunctionId",
            "baseName": "matched_function_id",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CalleeFunctionInfo.attributeTypeMap;
    }

    public constructor() {
    }
}
