/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CallerFunctionInfo {
    /**
    * Unique identifier of the function
    */
    'functionId': number;
    'matchedFunctionId': number | null;
    'dashboardUrl': string | null;
    /**
    * Indicates if the function is external
    */
    'isExternal'?: boolean;
    /**
    * Name of the calling function
    */
    'callerName': string;
    /**
    * Virtual address of the calling function
    */
    'callerVaddr': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "functionId",
            "baseName": "function_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "matchedFunctionId",
            "baseName": "matched_function_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "dashboardUrl",
            "baseName": "dashboard_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "isExternal",
            "baseName": "is_external",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "callerName",
            "baseName": "caller_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "callerVaddr",
            "baseName": "caller_vaddr",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CallerFunctionInfo.attributeTypeMap;
    }

    public constructor() {
    }
}
