/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Capability } from '../models/Capability';
import { HttpFile } from '../http/http';

export class Capabilities {
    /**
    * List of capabilities for a given analysis
    */
    'capabilities': Array<Capability>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "capabilities",
            "baseName": "capabilities",
            "type": "Array<Capability>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Capabilities.attributeTypeMap;
    }

    public constructor() {
    }
}
