/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Capability } from '../models/Capability';
import { HttpFile } from '../http/http';

export class CapabilitiesResult {
    /**
    * Capabilities found. A capability whose address no longer resolves within the analysis is omitted.
    */
    'capabilities': Array<Capability> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "capabilities",
            "baseName": "capabilities",
            "type": "Array<Capability>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CapabilitiesResult.attributeTypeMap;
    }

    public constructor() {
    }
}
