/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BinaryTaskStatus } from '../models/BinaryTaskStatus';
import { HttpFile } from '../http/http';

export class CheckSecurityChecksTaskResponse {
    'status': BinaryTaskStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "BinaryTaskStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CheckSecurityChecksTaskResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


