/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CollectionBinaryResponse } from '../models/CollectionBinaryResponse';
import { HttpFile } from '../http/http';

export class CollectionBinariesUpdateResponse {
    /**
    * Collection binaries
    */
    'binaries': Array<CollectionBinaryResponse>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "binaries",
            "baseName": "binaries",
            "type": "Array<CollectionBinaryResponse>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CollectionBinariesUpdateResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
