/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CollectionScope } from '../models/CollectionScope';
import { HttpFile } from '../http/http';

export class CollectionCreateRequest {
    'collectionName': string;
    'description': string;
    'collectionScope'?: CollectionScope;
    'tags'?: Array<string> | null;
    'binaries'?: Array<number> | null;
    'modelId': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "collectionName",
            "baseName": "collection_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "collectionScope",
            "baseName": "collection_scope",
            "type": "CollectionScope",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "binaries",
            "baseName": "binaries",
            "type": "Array<number>",
            "format": ""
        },
        {
            "name": "modelId",
            "baseName": "model_id",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CollectionCreateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


