/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CollectionScope } from '../models/CollectionScope';
import { HttpFile } from '../http/http';

export class CollectionUpdateRequest {
    'collectionName'?: string | null;
    'description'?: string | null;
    'collectionScope'?: CollectionScope | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "collectionName",
            "baseName": "collection_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "collectionScope",
            "baseName": "collection_scope",
            "type": "CollectionScope",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CollectionUpdateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


