/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CollectionSearchResult {
    /**
    * The ID of the collection
    */
    'collectionId': number;
    /**
    * The name of the collection
    */
    'collectionName': string;
    /**
    * The creation date of the collection
    */
    'createdAt': Date;
    /**
    * The description of the collection
    */
    'description': string;
    /**
    * The last update date of the collection
    */
    'lastUpdatedAt': Date;
    /**
    * The model ID of the binary
    */
    'modelId': number;
    /**
    * The name of the model
    */
    'modelName': string;
    /**
    * The owner of the collection
    */
    'ownedBy': string;
    /**
    * The scope of the collection
    */
    'scope': string;
    'size'?: number | null;
    'tags'?: Array<string> | null;
    'teamId'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "collectionId",
            "baseName": "collection_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "collectionName",
            "baseName": "collection_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastUpdatedAt",
            "baseName": "last_updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "modelId",
            "baseName": "model_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "modelName",
            "baseName": "model_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "ownedBy",
            "baseName": "owned_by",
            "type": "string",
            "format": ""
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "string",
            "format": ""
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "teamId",
            "baseName": "team_id",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CollectionSearchResult.attributeTypeMap;
    }

    public constructor() {
    }
}
