/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DataTypeEntry } from '../models/DataTypeEntry';
import { FunctionSignatureEntry } from '../models/FunctionSignatureEntry';
import { HttpFile } from '../http/http';

export class CopyFunctionSignaturesOutputBody {
    /**
    * The data types this analysis gained or had replaced, ordered by data_type_id. Empty when every type the copied signatures need was already stored unchanged.
    */
    'dataTypes': Array<DataTypeEntry> | null;
    /**
    * The stored signatures of the target functions, in request order.
    */
    'signatures': Array<FunctionSignatureEntry> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dataTypes",
            "baseName": "data_types",
            "type": "Array<DataTypeEntry>",
            "format": ""
        },
        {
            "name": "signatures",
            "baseName": "signatures",
            "type": "Array<FunctionSignatureEntry>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CopyFunctionSignaturesOutputBody.attributeTypeMap;
    }

    public constructor() {
    }
}
