/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateURLResponse {
    'analysisId': number;
    'binaryId': number;
    'sha256Hash': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "analysisId",
            "baseName": "analysis_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "binaryId",
            "baseName": "binary_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "sha256Hash",
            "baseName": "sha_256_hash",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateURLResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
