/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateIdentityInputBody {
    /**
    * Issuer URL (must be trusted by this organisation)
    */
    'issuerUrl': string;
    /**
    * External subject identifier from the issuer
    */
    'subject': string;
    /**
    * Internal user ID to link
    */
    'userId': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "issuerUrl",
            "baseName": "issuer_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return CreateIdentityInputBody.attributeTypeMap;
    }

    public constructor() {
    }
}
