/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Binary } from '../models/Binary';
import { HttpFile } from '../http/http';

export class CreateCollectionOutputBody {
    'binaries'?: Array<Binary> | null;
    'collectionId': number;
    'collectionName': string;
    'collectionScope': string;
    'createdAt': Date;
    'description': string;
    'tags'?: Array<string> | null;
    'teamId': number;
    'updatedAt': Date;
    'userId': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "binaries",
            "baseName": "binaries",
            "type": "Array<Binary>",
            "format": ""
        },
        {
            "name": "collectionId",
            "baseName": "collection_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "collectionName",
            "baseName": "collection_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "collectionScope",
            "baseName": "collection_scope",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "teamId",
            "baseName": "team_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return CreateCollectionOutputBody.attributeTypeMap;
    }

    public constructor() {
    }
}
