/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateArrayDataType } from '../models/CreateArrayDataType';
import { CreateBaseDataType } from '../models/CreateBaseDataType';
import { CreateBitfieldDataType } from '../models/CreateBitfieldDataType';
import { CreateEnumDataType } from '../models/CreateEnumDataType';
import { CreateFunctionDataType } from '../models/CreateFunctionDataType';
import { CreatePointerDataType } from '../models/CreatePointerDataType';
import { CreateStructDataType } from '../models/CreateStructDataType';
import { CreateTypedefDataType } from '../models/CreateTypedefDataType';
import { CreateUnionDataType } from '../models/CreateUnionDataType';
import { CreateUnknownDataType } from '../models/CreateUnknownDataType';
import { HttpFile } from '../http/http';

/**
* A data type to create. `kind` selects the variant and so which definition the type must carry.
*/
/**
 * @type CreateDataTypeEntry
 * Type
 * @export
 */
export type CreateDataTypeEntry = CreateArrayDataType | CreateBaseDataType | CreateBitfieldDataType | CreateEnumDataType | CreateFunctionDataType | CreatePointerDataType | CreateStructDataType | CreateTypedefDataType | CreateUnionDataType | CreateUnknownDataType;

/**
* @type CreateDataTypeEntryClass
    * A data type to create. `kind` selects the variant and so which definition the type must carry.
* @export
*/
export class CreateDataTypeEntryClass {
    static readonly discriminator: string | undefined = "kind";

    static readonly mapping: {[index: string]: string} | undefined = {
        "ARRAY": "CreateArrayDataType",
        "BASE": "CreateBaseDataType",
        "BITFIELD": "CreateBitfieldDataType",
        "ENUM": "CreateEnumDataType",
        "FUNCTION_DEFINITION": "CreateFunctionDataType",
        "POINTER": "CreatePointerDataType",
        "STRUCT": "CreateStructDataType",
        "TYPEDEF": "CreateTypedefDataType",
        "UNION": "CreateUnionDataType",
        "UNKNOWN": "CreateUnknownDataType",
    };
}









