/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DataTypeEntry } from '../models/DataTypeEntry';
import { HistoryActor } from '../models/HistoryActor';
import { HttpFile } from '../http/http';

export class DataTypeVersion {
    /**
    * When this version was written. Absent on a version that predates the recorded history.
    */
    'updatedAt'?: Date;
    /**
    * Who wrote this version. Absent on a version that predates the recorded history.
    */
    'updatedBy'?: HistoryActor;
    /**
    * The type as it stood in this version.
    */
    'value': DataTypeEntry;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedBy",
            "baseName": "updated_by",
            "type": "HistoryActor",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "DataTypeEntry",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DataTypeVersion.attributeTypeMap;
    }

    public constructor() {
    }
}
