/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ArrayDataType } from '../models/ArrayDataType';
import { BaseDataType } from '../models/BaseDataType';
import { BitfieldDataType } from '../models/BitfieldDataType';
import { EnumDataType } from '../models/EnumDataType';
import { FunctionDataType } from '../models/FunctionDataType';
import { PointerDataType } from '../models/PointerDataType';
import { StructDataType } from '../models/StructDataType';
import { TypedefDataType } from '../models/TypedefDataType';
import { UnionDataType } from '../models/UnionDataType';
import { UnknownDataType } from '../models/UnknownDataType';
import { HttpFile } from '../http/http';

/**
* A data type extracted from the binary. `kind` selects the variant and so which definition the type carries.
*/
/**
 * @type DataTypeEntry
 * Type
 * @export
 */
export type DataTypeEntry = ArrayDataType | BaseDataType | BitfieldDataType | EnumDataType | FunctionDataType | PointerDataType | StructDataType | TypedefDataType | UnionDataType | UnknownDataType;

/**
* @type DataTypeEntryClass
    * A data type extracted from the binary. `kind` selects the variant and so which definition the type carries.
* @export
*/
export class DataTypeEntryClass {
    static readonly discriminator: string | undefined = "kind";

    static readonly mapping: {[index: string]: string} | undefined = {
        "ARRAY": "ArrayDataType",
        "BASE": "BaseDataType",
        "BITFIELD": "BitfieldDataType",
        "ENUM": "EnumDataType",
        "FUNCTION_DEFINITION": "FunctionDataType",
        "POINTER": "PointerDataType",
        "STRUCT": "StructDataType",
        "TYPEDEF": "TypedefDataType",
        "UNION": "UnionDataType",
        "UNKNOWN": "UnknownDataType",
    };
}









