/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DieMatch {
    /**
    * Canonical name of the matched signature/technology (e.g., \'UPX\', \'GCC\', \'MSVC\').
    */
    'name': string;
    /**
    * Category assigned by DIE for the match (e.g., \'compiler\', \'packer\', \'file\').
    */
    'type': string;
    /**
    * Human-readable description from DIE\'s \'string\' field; suitable for UI/logs, not for parsing.
    */
    'display': string;
    /**
    * Extracted version string when available; may be empty/None if unknown.
    */
    'version': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "display",
            "baseName": "display",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DieMatch.attributeTypeMap;
    }

    public constructor() {
    }
}
