/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReportEvent } from '../models/ReportEvent';
import { HttpFile } from '../http/http';

export class DnsQuery {
    'cnameChain'?: Array<string> | null;
    'domain': string;
    'events'?: Array<ReportEvent> | null;
    'minTtl'?: number;
    'resolvedIps'?: Array<string> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cnameChain",
            "baseName": "cname_chain",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string",
            "format": ""
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<ReportEvent>",
            "format": ""
        },
        {
            "name": "minTtl",
            "baseName": "min_ttl",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "resolvedIps",
            "baseName": "resolved_ips",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DnsQuery.attributeTypeMap;
    }

    public constructor() {
    }
}
