/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AnalysisLogs } from '../models/AnalysisLogs';
import { HttpFile } from '../http/http';

export class DynamicExecutionMetadata {
    /**
    * Sandbox status log messages captured during the run. Empty when none have been captured yet.
    */
    'logs': AnalysisLogs;
    /**
    * Run status. UNINITIALISED means this analysis has never had a run triggered.
    */
    'status': DynamicExecutionMetadataStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "logs",
            "baseName": "logs",
            "type": "AnalysisLogs",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "DynamicExecutionMetadataStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DynamicExecutionMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum DynamicExecutionMetadataStatusEnum {
    Uninitialised = 'UNINITIALISED',
    Pending = 'PENDING',
    Running = 'RUNNING',
    Completed = 'COMPLETED',
    Failed = 'FAILED',
    UnknownDefaultOpenApi = '11184809'
}

