/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ELFRelocation {
    'address': number;
    'type': string;
    'size': number;
    'addend': number;
    'symbolName': string;
    'isDynamic': boolean;
    'isPltgot': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number",
            "format": ""
        },
        {
            "name": "addend",
            "baseName": "addend",
            "type": "number",
            "format": ""
        },
        {
            "name": "symbolName",
            "baseName": "symbol_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "isDynamic",
            "baseName": "is_dynamic",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isPltgot",
            "baseName": "is_pltgot",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ELFRelocation.attributeTypeMap;
    }

    public constructor() {
    }
}
