/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Enumeration {
    /**
    * Type of artifact that the enumeration is associated with
    */
    'artifactType'?: string;
    'lastChange'?: string | null;
    /**
    * Dictionary of enumeration members and their values
    */
    'members': { [key: string]: number; };
    /**
    * Name of the enumeration
    */
    'name': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "artifactType",
            "baseName": "artifact_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastChange",
            "baseName": "last_change",
            "type": "string",
            "format": ""
        },
        {
            "name": "members",
            "baseName": "members",
            "type": "{ [key: string]: number; }",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Enumeration.attributeTypeMap;
    }

    public constructor() {
    }
}
