/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ErrorBody {
    /**
    * Stable, machine-readable error code. Versioned and documented.
    */
    'code': ErrorBodyCodeEnum;
    /**
    * Additional context where helpful (quota numbers, validation specifics, etc.).
    */
    'detail'?: string;
    /**
    * Link to documentation explaining this error and resolution steps.
    */
    'docUrl'?: string;
    /**
    * Human-readable summary. Never contains internals. Suitable for direct display.
    */
    'message': string;
    /**
    * Correlation ID from the request. Quote this in support requests.
    */
    'traceId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "ErrorBodyCodeEnum",
            "format": ""
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "string",
            "format": ""
        },
        {
            "name": "docUrl",
            "baseName": "doc_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "traceId",
            "baseName": "trace_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ErrorBody.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ErrorBodyCodeEnum {
    AccessDenied = 'ACCESS_DENIED',
    AgentBudgetExceeded = 'AGENT_BUDGET_EXCEEDED',
    AgentDefinitionNotFound = 'AGENT_DEFINITION_NOT_FOUND',
    AgentInvalidStartingInput = 'AGENT_INVALID_STARTING_INPUT',
    AgentMemoryInvalidScope = 'AGENT_MEMORY_INVALID_SCOPE',
    AgentMemoryNotFound = 'AGENT_MEMORY_NOT_FOUND',
    AgentMemoryVersionConflict = 'AGENT_MEMORY_VERSION_CONFLICT',
    AgentNoPendingQuestion = 'AGENT_NO_PENDING_QUESTION',
    AgentRunNotFound = 'AGENT_RUN_NOT_FOUND',
    AlreadyExists = 'ALREADY_EXISTS',
    AnalysisNotReady = 'ANALYSIS_NOT_READY',
    BadRequest = 'BAD_REQUEST',
    ClientClosedRequest = 'CLIENT_CLOSED_REQUEST',
    Conflict = 'CONFLICT',
    ConversationNotFound = 'CONVERSATION_NOT_FOUND',
    DomainAlreadyClaimed = 'DOMAIN_ALREADY_CLAIMED',
    DomainVerificationPending = 'DOMAIN_VERIFICATION_PENDING',
    DynamicExecutionIncomplete = 'DYNAMIC_EXECUTION_INCOMPLETE',
    EmailNotVerified = 'EMAIL_NOT_VERIFIED',
    ExternalUser = 'EXTERNAL_USER',
    Forbidden = 'FORBIDDEN',
    GatewayTimeout = 'GATEWAY_TIMEOUT',
    GroupHasMembers = 'GROUP_HAS_MEMBERS',
    InsufficientCredits = 'INSUFFICIENT_CREDITS',
    InternalError = 'INTERNAL_ERROR',
    InternalIssuer = 'INTERNAL_ISSUER',
    InvalidConversationId = 'INVALID_CONVERSATION_ID',
    InvalidCredentials = 'INVALID_CREDENTIALS',
    InvalidInviteCode = 'INVALID_INVITE_CODE',
    InvalidResetCode = 'INVALID_RESET_CODE',
    LastOrgOwner = 'LAST_ORG_OWNER',
    LastTeamAdmin = 'LAST_TEAM_ADMIN',
    LastTeamMember = 'LAST_TEAM_MEMBER',
    LinkedToOrg = 'LINKED_TO_ORG',
    MethodNotAllowed = 'METHOD_NOT_ALLOWED',
    NotAcceptable = 'NOT_ACCEPTABLE',
    NotFound = 'NOT_FOUND',
    NoActiveRun = 'NO_ACTIVE_RUN',
    NoPendingConfirmation = 'NO_PENDING_CONFIRMATION',
    OidcDiscoveryFailed = 'OIDC_DISCOVERY_FAILED',
    PasswordResetRequired = 'PASSWORD_RESET_REQUIRED',
    PaymentRequired = 'PAYMENT_REQUIRED',
    ReportRenderFailed = 'REPORT_RENDER_FAILED',
    RequestEntityTooLarge = 'REQUEST_ENTITY_TOO_LARGE',
    RunAlreadyActive = 'RUN_ALREADY_ACTIVE',
    SelfDeletionNotAllowed = 'SELF_DELETION_NOT_ALLOWED',
    ServiceUnavailable = 'SERVICE_UNAVAILABLE',
    TokenExpired = 'TOKEN_EXPIRED',
    TokenReused = 'TOKEN_REUSED',
    TooManyRequests = 'TOO_MANY_REQUESTS',
    Unauthorized = 'UNAUTHORIZED',
    UnsupportedMediaType = 'UNSUPPORTED_MEDIA_TYPE',
    ValidationFailed = 'VALIDATION_FAILED',
    VerificationExpired = 'VERIFICATION_EXPIRED',
    VerificationNotFound = 'VERIFICATION_NOT_FOUND',
    UnknownDefaultOpenApi = '11184809'
}

