/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SourceDeltaEvent } from '../models/SourceDeltaEvent';
import { HttpFile } from '../http/http';

export class EventSourceDelta {
    'data': SourceDeltaEvent;
    /**
    * The event name.
    */
    'event': EventSourceDeltaEventEnum;
    /**
    * The event ID.
    */
    'id'?: number;
    /**
    * The retry time in milliseconds.
    */
    'retry'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "SourceDeltaEvent",
            "format": ""
        },
        {
            "name": "event",
            "baseName": "event",
            "type": "EventSourceDeltaEventEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "retry",
            "baseName": "retry",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EventSourceDelta.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum EventSourceDeltaEventEnum {
    SourceDelta = 'source_delta',
    UnknownDefaultOpenApi = '11184809'
}

