/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProseEvent } from '../models/ProseEvent';
import { HttpFile } from '../http/http';

export class EventProse {
    'data': ProseEvent;
    /**
    * The event name.
    */
    'event': EventProseEventEnum;
    /**
    * The event ID.
    */
    'id'?: number;
    /**
    * The retry time in milliseconds.
    */
    'retry'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "ProseEvent",
            "format": ""
        },
        {
            "name": "event",
            "baseName": "event",
            "type": "EventProseEventEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "retry",
            "baseName": "retry",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EventProse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum EventProseEventEnum {
    Prose = 'prose',
    UnknownDefaultOpenApi = '11184809'
}

