/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ExecutionFinding } from '../models/ExecutionFinding';
import { HttpFile } from '../http/http';

export class ExecutionScanResult {
    /**
    * Analysis the run was performed against
    */
    'analysisId': number;
    /**
    * Functions with execution-related evidence, sorted by whether they execute code, then confidence, then evidence count
    */
    'findings'?: Array<ExecutionFinding> | null;
    /**
    * Functions the run considered
    */
    'totalFunctions': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "analysisId",
            "baseName": "analysis_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "findings",
            "baseName": "findings",
            "type": "Array<ExecutionFinding>",
            "format": ""
        },
        {
            "name": "totalFunctions",
            "baseName": "total_functions",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ExecutionScanResult.attributeTypeMap;
    }

    public constructor() {
    }
}
