/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ExecutionCall {
    /**
    * Name of the called function
    */
    'calleeName': string;
    /**
    * Execution category of the match
    */
    'category': ExecutionCallCategoryEnum;
    /**
    * Detection tier that produced the match
    */
    'how': ExecutionCallHowEnum;
    /**
    * Name or token that matched
    */
    'matchedName': string;
    /**
    * Execution source the match belongs to
    */
    'source': ExecutionCallSourceEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "calleeName",
            "baseName": "callee_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "ExecutionCallCategoryEnum",
            "format": ""
        },
        {
            "name": "how",
            "baseName": "how",
            "type": "ExecutionCallHowEnum",
            "format": ""
        },
        {
            "name": "matchedName",
            "baseName": "matched_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "ExecutionCallSourceEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExecutionCall.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ExecutionCallCategoryEnum {
    DynamicResolve = 'dynamic-resolve',
    Hooking = 'hooking',
    Injection = 'injection',
    MemoryExec = 'memory-exec',
    ModuleLoad = 'module-load',
    ProcessControl = 'process-control',
    ProcessCreate = 'process-create',
    ScriptExec = 'script-exec',
    Shellcode = 'shellcode',
    ThreadCreate = 'thread-create',
    UnknownDefaultOpenApi = '11184809'
}
export enum ExecutionCallHowEnum {
    Api = 'api',
    CppClassToken = 'cpp-class-token',
    GenericKeyword = 'generic-keyword',
    UnknownDefaultOpenApi = '11184809'
}
export enum ExecutionCallSourceEnum {
    Boost = 'boost',
    Cpp = 'cpp',
    CppStdlib = 'cpp-stdlib',
    Generic = 'generic',
    Libc = 'libc',
    Qt = 'qt',
    ScriptEngine = 'script-engine',
    Windows = 'windows',
    UnknownDefaultOpenApi = '11184809'
}

