/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ExtractedFileEntry {
    'fileHash'?: string | null;
    'fileSize': number;
    'fileType'?: string | null;
    'filename': string | null;
    'isPe'?: boolean;
    'mimeType'?: string | null;
    'reason'?: string | null;
    'seqNum': number;
    'sha256'?: string | null;
    'zipFilename': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fileHash",
            "baseName": "file_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileSize",
            "baseName": "file_size",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "fileType",
            "baseName": "file_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string",
            "format": ""
        },
        {
            "name": "isPe",
            "baseName": "is_pe",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "mimeType",
            "baseName": "mime_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "seqNum",
            "baseName": "seq_num",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "sha256",
            "baseName": "sha256",
            "type": "string",
            "format": ""
        },
        {
            "name": "zipFilename",
            "baseName": "zip_filename",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExtractedFileEntry.attributeTypeMap;
    }

    public constructor() {
    }
}
