/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FeedbackOutputBody {
    /**
    * The sentiment the caller recorded, or null when they have not left any
    */
    'sentiment': FeedbackOutputBodySentimentEnum | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sentiment",
            "baseName": "sentiment",
            "type": "FeedbackOutputBodySentimentEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FeedbackOutputBody.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum FeedbackOutputBodySentimentEnum {
    Positive = 'POSITIVE',
    Neutral = 'NEUTRAL',
    Negative = 'NEGATIVE',
    UnknownDefaultOpenApi = '11184809'
}

