/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FilesystemExplainedFunction {
    /**
    * Role this function plays in the filesystem access
    */
    'description': string;
    /**
    * ID of the function
    */
    'functionId': number;
    /**
    * Name of the function
    */
    'functionName': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "functionId",
            "baseName": "function_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "functionName",
            "baseName": "function_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FilesystemExplainedFunction.attributeTypeMap;
    }

    public constructor() {
    }
}
