/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FileHashes {
    'md5': string | null;
    'sha1': string | null;
    'sha256': string | null;
    'sha512': string | null;
    'sha3224': string | null;
    'sha3256': string | null;
    'sha3384': string | null;
    'sha3512': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "md5",
            "baseName": "md5",
            "type": "string",
            "format": ""
        },
        {
            "name": "sha1",
            "baseName": "sha1",
            "type": "string",
            "format": ""
        },
        {
            "name": "sha256",
            "baseName": "sha256",
            "type": "string",
            "format": ""
        },
        {
            "name": "sha512",
            "baseName": "sha512",
            "type": "string",
            "format": ""
        },
        {
            "name": "sha3224",
            "baseName": "sha3_224",
            "type": "string",
            "format": ""
        },
        {
            "name": "sha3256",
            "baseName": "sha3_256",
            "type": "string",
            "format": ""
        },
        {
            "name": "sha3384",
            "baseName": "sha3_384",
            "type": "string",
            "format": ""
        },
        {
            "name": "sha3512",
            "baseName": "sha3_512",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FileHashes.attributeTypeMap;
    }

    public constructor() {
    }
}
