/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FileHashes } from '../models/FileHashes';
import { HttpFile } from '../http/http';

export class FileMetadata {
    'size': number;
    'friendlySize': string;
    'entropy': number;
    'hashes': FileHashes;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "size",
            "baseName": "size",
            "type": "number",
            "format": ""
        },
        {
            "name": "friendlySize",
            "baseName": "friendly_size",
            "type": "string",
            "format": ""
        },
        {
            "name": "entropy",
            "baseName": "entropy",
            "type": "number",
            "format": ""
        },
        {
            "name": "hashes",
            "baseName": "hashes",
            "type": "FileHashes",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FileMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}
