/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FormFile {
    'contentType': string | null;
    'filename': string | null;
    'isSet': boolean;
    'size': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "contentType",
            "baseName": "ContentType",
            "type": "string",
            "format": ""
        },
        {
            "name": "filename",
            "baseName": "Filename",
            "type": "string",
            "format": ""
        },
        {
            "name": "isSet",
            "baseName": "IsSet",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "size",
            "baseName": "Size",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return FormFile.attributeTypeMap;
    }

    public constructor() {
    }
}
