/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FunctionString {
    /**
    * The value of the string literal
    */
    'value': string;
    /**
    * The vaddr of the string value
    */
    'vaddr': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "vaddr",
            "baseName": "vaddr",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FunctionString.attributeTypeMap;
    }

    public constructor() {
    }
}
