/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FunctionNameInput } from '../models/FunctionNameInput';
import { HttpFile } from '../http/http';

export class FunctionNameConfidenceBody {
    /**
    * List of function ids and the function names they want to check confidence for
    */
    'functions'?: Array<FunctionNameInput>;
    /**
    * Flag to match only to a debug function
    */
    'isDebug'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "functions",
            "baseName": "functions",
            "type": "Array<FunctionNameInput>",
            "format": ""
        },
        {
            "name": "isDebug",
            "baseName": "is_debug",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FunctionNameConfidenceBody.attributeTypeMap;
    }

    public constructor() {
    }
}
