/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FunctionMatchingFilters {
    /**
    * ID\'s of binaries to limit the search to, if empty, search all scoped binaries
    */
    'binaryIds'?: Array<number>;
    /**
    * ID\'s of collections to limit the search to, if empty, search all scoped collections
    */
    'collectionIds'?: Array<number>;
    /**
    * Limit the search to specific debug types, if empty, search all scoped debug & non-debug functions
    */
    'debugTypes'?: Array<FunctionMatchingFiltersDebugTypesEnum>;
    /**
    * ID\'s of functions to limit the search to, if empty, search all scoped functions
    */
    'functionIds'?: Array<number>;
    /**
    * ID\'s of users to limit the search to, if empty, search all scoped users
    */
    'userIds'?: Array<number>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "binaryIds",
            "baseName": "binary_ids",
            "type": "Array<number>",
            "format": ""
        },
        {
            "name": "collectionIds",
            "baseName": "collection_ids",
            "type": "Array<number>",
            "format": ""
        },
        {
            "name": "debugTypes",
            "baseName": "debug_types",
            "type": "Array<FunctionMatchingFiltersDebugTypesEnum>",
            "format": ""
        },
        {
            "name": "functionIds",
            "baseName": "function_ids",
            "type": "Array<number>",
            "format": "int64"
        },
        {
            "name": "userIds",
            "baseName": "user_ids",
            "type": "Array<number>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FunctionMatchingFilters.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum FunctionMatchingFiltersDebugTypesEnum {
    User = 'USER',
    System = 'SYSTEM',
    External = 'EXTERNAL'
}

