/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FunctionBoundary {
    'mangledName': string;
    'startAddress': number;
    'endAddress': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mangledName",
            "baseName": "mangled_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "startAddress",
            "baseName": "start_address",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "endAddress",
            "baseName": "end_address",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return FunctionBoundary.attributeTypeMap;
    }

    public constructor() {
    }
}
