/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FunctionInfoInputFuncDepsInner } from '../models/FunctionInfoInputFuncDepsInner';
import { FunctionTypeInput } from '../models/FunctionTypeInput';
import { HttpFile } from '../http/http';

export class FunctionInfoInput {
    'funcTypes'?: FunctionTypeInput | null;
    /**
    * List of function dependencies
    */
    'funcDeps': Array<FunctionInfoInputFuncDepsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "funcTypes",
            "baseName": "func_types",
            "type": "FunctionTypeInput",
            "format": ""
        },
        {
            "name": "funcDeps",
            "baseName": "func_deps",
            "type": "Array<FunctionInfoInputFuncDepsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FunctionInfoInput.attributeTypeMap;
    }

    public constructor() {
    }
}
