/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FunctionBlockResponse } from '../models/FunctionBlockResponse';
import { FunctionLocalVariableResponse } from '../models/FunctionLocalVariableResponse';
import { FunctionParamResponse } from '../models/FunctionParamResponse';
import { HttpFile } from '../http/http';

/**
* Response for returning disassembly of a function.
*/
export class FunctionBlocksResponse {
    /**
    * Disassembly is broken into control flow blocks
    */
    'blocks': Array<FunctionBlockResponse>;
    /**
    * Local variables associated with this function
    */
    'localVariables': Array<FunctionLocalVariableResponse>;
    'overviewComment': string | null;
    /**
    * Params associated with this function
    */
    'params': Array<FunctionParamResponse>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "blocks",
            "baseName": "blocks",
            "type": "Array<FunctionBlockResponse>",
            "format": ""
        },
        {
            "name": "localVariables",
            "baseName": "local_variables",
            "type": "Array<FunctionLocalVariableResponse>",
            "format": ""
        },
        {
            "name": "overviewComment",
            "baseName": "overview_comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "params",
            "baseName": "params",
            "type": "Array<FunctionParamResponse>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FunctionBlocksResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
