/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FunctionRenameMap {
    /**
    * The ID of the function to rename
    */
    'functionId': number;
    /**
    * The new name for the function
    */
    'newName'?: string;
    'newMangledName'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "functionId",
            "baseName": "function_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "newName",
            "baseName": "new_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "newMangledName",
            "baseName": "new_mangled_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FunctionRenameMap.attributeTypeMap;
    }

    public constructor() {
    }
}
