/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DataTypeEntry } from '../models/DataTypeEntry';
import { SignatureParameterEntry } from '../models/SignatureParameterEntry';
import { HttpFile } from '../http/http';

export class FunctionSignatureBody {
    /**
    * Calling convention, when the producer reported one.
    */
    'callingConvention'?: string;
    /**
    * When this signature was extracted.
    */
    'createdAt'?: Date;
    /**
    * The types the signature names — its parameter types and its return type — ordered by data_type_id. Each entry is identical to the one the data types endpoints serve for that id. Returned only when include_data_types is true.
    */
    'dataTypes'?: Array<DataTypeEntry> | null;
    'functionId': number;
    /**
    * Current name of the function.
    */
    'functionName': string;
    /**
    * Whether a signature was extracted for this function. False is a normal result: no signature is recorded unless data type extraction ran for the analysis, and thunks and external functions are skipped when it does.
    */
    'hasSignature': boolean;
    /**
    * Parameters in argument order. Empty with has_signature true means the function is known to take no arguments.
    */
    'parameters': Array<SignatureParameterEntry> | null;
    /**
    * Return type, resolvable against the analysis data types list. Absent for an unresolved return type.
    */
    'returnDataTypeId'?: number;
    /**
    * The function this signature was copied from, when it was transferred rather than extracted.
    */
    'sourceFunctionId'?: number;
    /**
    * Where this signature came from.
    */
    'sourceType'?: FunctionSignatureBodySourceTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "callingConvention",
            "baseName": "calling_convention",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "dataTypes",
            "baseName": "data_types",
            "type": "Array<DataTypeEntry>",
            "format": ""
        },
        {
            "name": "functionId",
            "baseName": "function_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "functionName",
            "baseName": "function_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasSignature",
            "baseName": "has_signature",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "parameters",
            "baseName": "parameters",
            "type": "Array<SignatureParameterEntry>",
            "format": ""
        },
        {
            "name": "returnDataTypeId",
            "baseName": "return_data_type_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "sourceFunctionId",
            "baseName": "source_function_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "sourceType",
            "baseName": "source_type",
            "type": "FunctionSignatureBodySourceTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FunctionSignatureBody.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum FunctionSignatureBodySourceTypeEnum {
    System = 'SYSTEM',
    User = 'USER',
    AutoUnstrip = 'AUTO_UNSTRIP',
    UnknownDefaultOpenApi = '11184809'
}

