/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StringSource } from '../models/StringSource';
import { HttpFile } from '../http/http';

export class FunctionString {
    /**
    * The value of the string literal
    */
    'value': string;
    /**
    * The vaddr of the string value
    */
    'vaddr': number;
    /**
    * The source of the string
    */
    'source'?: StringSource;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "vaddr",
            "baseName": "vaddr",
            "type": "number",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "StringSource",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FunctionString.attributeTypeMap;
    }

    public constructor() {
    }
}


