/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FunctionMatchingResultWithBestMatch } from '../models/FunctionMatchingResultWithBestMatch';
import { HttpFile } from '../http/http';

export class FunctionMatchingBatchResponse {
    /**
    * Progress of the matching operation, represented as a percentage
    */
    'progress'?: number;
    'status'?: string | null;
    'totalTime'?: number | null;
    'errorMessage'?: string | null;
    'currentPage'?: number | null;
    'totalPages'?: number | null;
    'matches'?: Array<FunctionMatchingResultWithBestMatch> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "progress",
            "baseName": "progress",
            "type": "number",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "totalTime",
            "baseName": "total_time",
            "type": "number",
            "format": ""
        },
        {
            "name": "errorMessage",
            "baseName": "error_message",
            "type": "string",
            "format": ""
        },
        {
            "name": "currentPage",
            "baseName": "current_page",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalPages",
            "baseName": "total_pages",
            "type": "number",
            "format": ""
        },
        {
            "name": "matches",
            "baseName": "matches",
            "type": "Array<FunctionMatchingResultWithBestMatch>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FunctionMatchingBatchResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
