/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FunctionRename {
    /**
    * The new mangled name for the function
    */
    'newMangledName': string;
    /**
    * The new name for the function
    */
    'newName': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "newMangledName",
            "baseName": "new_mangled_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "newName",
            "baseName": "new_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FunctionRename.attributeTypeMap;
    }

    public constructor() {
    }
}
