/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EvidenceEffect } from '../models/EvidenceEffect';
import { FunctionSimilarity } from '../models/FunctionSimilarity';
import { HttpFile } from '../http/http';

/**
* Function-similarity results suggestive of a capability.
*/
export class FunctionSimilarityEvidence {
    'evidenceKind'?: FunctionSimilarityEvidenceEvidenceKindEnum;
    'kind'?: FunctionSimilarityEvidenceKindEnum;
    'effect': EvidenceEffect;
    'strength'?: FunctionSimilarityEvidenceStrengthEnum;
    'similarities': Array<FunctionSimilarity>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "evidenceKind",
            "baseName": "evidence_kind",
            "type": "FunctionSimilarityEvidenceEvidenceKindEnum",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "FunctionSimilarityEvidenceKindEnum",
            "format": ""
        },
        {
            "name": "effect",
            "baseName": "effect",
            "type": "EvidenceEffect",
            "format": ""
        },
        {
            "name": "strength",
            "baseName": "strength",
            "type": "FunctionSimilarityEvidenceStrengthEnum",
            "format": ""
        },
        {
            "name": "similarities",
            "baseName": "similarities",
            "type": "Array<FunctionSimilarity>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FunctionSimilarityEvidence.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum FunctionSimilarityEvidenceEvidenceKindEnum {
    FunctionSimilarity = 'function_similarity',
    UnknownDefaultOpenApi = '11184809'
}
export enum FunctionSimilarityEvidenceKindEnum {
    DeterministicDerivation = 'deterministic_derivation',
    UnknownDefaultOpenApi = '11184809'
}
export enum FunctionSimilarityEvidenceStrengthEnum {
    Indirect = 'indirect',
    UnknownDefaultOpenApi = '11184809'
}

