/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum FunctionSourceType {
    System = 'SYSTEM',
    User = 'USER',
    External = 'EXTERNAL',
    AutoUnstrip = 'AUTO_UNSTRIP',
    AiUnstrip = 'AI_UNSTRIP'
}
