/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GenerationStatusList } from '../models/GenerationStatusList';
import { HttpFile } from '../http/http';

export class GenerateFunctionDataTypes {
    /**
    * List of function data types information that are either already generated, or now queued for generation
    */
    'dataTypesList': GenerationStatusList;
    /**
    * [DEPRECATED] This value has been replaced with the `data_types_list` field
    * @deprecated
    */
    'queued': boolean;
    /**
    * [DEPRECATED] This value has been replaced with the `data_types_list` field
    * @deprecated
    */
    'reference': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dataTypesList",
            "baseName": "data_types_list",
            "type": "GenerationStatusList",
            "format": ""
        },
        {
            "name": "queued",
            "baseName": "queued",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GenerateFunctionDataTypes.attributeTypeMap;
    }

    public constructor() {
    }
}
