/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FunctionDataTypesStatus } from '../models/FunctionDataTypesStatus';
import { HttpFile } from '../http/http';

export class GenerationStatusList {
    /**
    * Total number of functions in analysis
    */
    'totalCount'?: number;
    /**
    * Total number of functions with data types
    */
    'totalDataTypesCount'?: number;
    /**
    * List of function data types information
    */
    'items': Array<FunctionDataTypesStatus>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalDataTypesCount",
            "baseName": "total_data_types_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<FunctionDataTypesStatus>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GenerationStatusList.attributeTypeMap;
    }

    public constructor() {
    }
}
