/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AiDecompilationTaskStatus } from '../models/AiDecompilationTaskStatus';
import { FunctionMappingFull } from '../models/FunctionMappingFull';
import { InverseFunctionMapItem } from '../models/InverseFunctionMapItem';
import { HttpFile } from '../http/http';

export class GetAiDecompilationTask {
    /**
    * The status of the AI decompilation task
    */
    'status': AiDecompilationTaskStatus;
    'decompilation': string | null;
    'rawDecompilation': string | null;
    'functionMapping': { [key: string]: InverseFunctionMapItem; } | null;
    'functionMappingFull': FunctionMappingFull | null;
    'summary'?: string | null;
    'aiSummary'?: string | null;
    'rawAiSummary'?: string | null;
    'predictedFunctionName'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "AiDecompilationTaskStatus",
            "format": ""
        },
        {
            "name": "decompilation",
            "baseName": "decompilation",
            "type": "string",
            "format": ""
        },
        {
            "name": "rawDecompilation",
            "baseName": "raw_decompilation",
            "type": "string",
            "format": ""
        },
        {
            "name": "functionMapping",
            "baseName": "function_mapping",
            "type": "{ [key: string]: InverseFunctionMapItem; }",
            "format": ""
        },
        {
            "name": "functionMappingFull",
            "baseName": "function_mapping_full",
            "type": "FunctionMappingFull",
            "format": ""
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "aiSummary",
            "baseName": "ai_summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "rawAiSummary",
            "baseName": "raw_ai_summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "predictedFunctionName",
            "baseName": "predicted_function_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetAiDecompilationTask.attributeTypeMap;
    }

    public constructor() {
    }
}


