/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GetConfigOutputBody {
    /**
    * Source languages AI decompilation does not support
    */
    'aiDecompilerUnsupportedLanguages': Array<string> | null;
    /**
    * Largest binary the calling user may submit for analysis, in bytes
    */
    'maxFileSizeBytes': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "aiDecompilerUnsupportedLanguages",
            "baseName": "ai_decompiler_unsupported_languages",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "maxFileSizeBytes",
            "baseName": "max_file_size_bytes",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return GetConfigOutputBody.attributeTypeMap;
    }

    public constructor() {
    }
}
