/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DieMatch } from '../models/DieMatch';
import { HttpFile } from '../http/http';

export class GetDieInfoOutputBody {
    /**
    * Signatures Detect It Easy recognised in the binary
    */
    'matches': Array<DieMatch> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "matches",
            "baseName": "matches",
            "type": "Array<DieMatch>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetDieInfoOutputBody.attributeTypeMap;
    }

    public constructor() {
    }
}
