/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class HistoryEntry {
    /**
    * Username of the user who made the change
    */
    'changeMadeBy': string;
    /**
    * When this name change was recorded
    */
    'createdAt': Date;
    /**
    * Function name at this point in history
    */
    'functionName': string;
    /**
    * History record ID
    */
    'historyId': number;
    /**
    * Whether the function had debug info
    */
    'isDebug': boolean;
    /**
    * Mangled function name
    */
    'mangledName'?: string;
    /**
    * Source of the rename (USER, SYSTEM, AI_UNSTRIP, etc.)
    */
    'sourceType': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "changeMadeBy",
            "baseName": "change_made_by",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "functionName",
            "baseName": "function_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "historyId",
            "baseName": "history_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "isDebug",
            "baseName": "is_debug",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "mangledName",
            "baseName": "mangled_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourceType",
            "baseName": "source_type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HistoryEntry.attributeTypeMap;
    }

    public constructor() {
    }
}
