/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ImportModel {
    'numberOfImports': number;
    'imports': Array<{ [key: string]: { [key: string]: number; }; }>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "numberOfImports",
            "baseName": "number_of_imports",
            "type": "number",
            "format": ""
        },
        {
            "name": "imports",
            "baseName": "imports",
            "type": "Array<{ [key: string]: { [key: string]: number; }; }>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ImportModel.attributeTypeMap;
    }

    public constructor() {
    }
}
