/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Addr } from '../models/Addr';
import { HttpFile } from '../http/http';

export class InverseFunctionMapItem {
    'name': string;
    'addr': Addr | null;
    'isExternal'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "addr",
            "baseName": "addr",
            "type": "Addr",
            "format": ""
        },
        {
            "name": "isExternal",
            "baseName": "is_external",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InverseFunctionMapItem.attributeTypeMap;
    }

    public constructor() {
    }
}
