/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class IOC {
    /**
    * Type of the IOC
    */
    'type': IOCTypeEnum;
    /**
    * Value of the IOC
    */
    'value': string;
    /**
    * Description of the IOC
    */
    'description': string;
    'source'?: string | null;
    'functionId'?: number | null;
    'functionName'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "IOCTypeEnum",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string",
            "format": ""
        },
        {
            "name": "functionId",
            "baseName": "function_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "functionName",
            "baseName": "function_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IOC.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum IOCTypeEnum {
    Ip = 'ip',
    Domain = 'domain',
    Url = 'url',
    Usernames = 'usernames',
    Passwords = 'passwords',
    FileHash = 'file_hash',
    Mutex = 'mutex',
    RegistryKey = 'registry_key',
    Filename = 'filename',
    Email = 'email',
    C2Endpoint = 'c2_endpoint',
    UserAgent = 'user_agent',
    PemKey = 'pem_key',
    SshKey = 'ssh_key',
    NetworkPort = 'network_port',
    Ja3 = 'ja3',
    SslCertFingerprint = 'ssl_cert_fingerprint',
    HttpHeader = 'http_header',
    Service = 'service',
    ScheduledTask = 'scheduled_task',
    PeHeader = 'pe_header',
    Entropy = 'entropy',
    Other = 'other'
}

