/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class IssuerAllowedDomain {
    /**
    * DNS TXT challenge token. Add a TXT record at _reveng-verification.<domain> with this value.
    */
    'challengeToken'?: string;
    'createdAt': Date;
    /**
    * Email domain (e.g. acme.com)
    */
    'domain': string;
    'issuerAllowedDomainId': number;
    'organisationIssuerId': number;
    /**
    * Domain ownership verification status: PENDING, VERIFIED, or FAILED
    */
    'verificationStatus': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "challengeToken",
            "baseName": "challenge_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string",
            "format": ""
        },
        {
            "name": "issuerAllowedDomainId",
            "baseName": "issuer_allowed_domain_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "organisationIssuerId",
            "baseName": "organisation_issuer_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "verificationStatus",
            "baseName": "verification_status",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IssuerAllowedDomain.attributeTypeMap;
    }

    public constructor() {
    }
}
