/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DataTypeFunctionEntry } from '../models/DataTypeFunctionEntry';
import { HttpFile } from '../http/http';

export class ListDataTypeFunctionsBody {
    /**
    * The page of matching functions, in ascending function ID order. Empty when no function uses the type.
    */
    'items': Array<DataTypeFunctionEntry>;
    /**
    * Pass as after_function_id to fetch the next page. Absent on the last page.
    */
    'nextAfterFunctionId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<DataTypeFunctionEntry>",
            "format": ""
        },
        {
            "name": "nextAfterFunctionId",
            "baseName": "next_after_function_id",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ListDataTypeFunctionsBody.attributeTypeMap;
    }

    public constructor() {
    }
}
