/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MatchedFunction {
    'functionId': number;
    'binaryId': number;
    'functionName': string;
    'functionVaddr': number;
    'mangledName': string;
    'debug': boolean;
    'binaryName': string;
    'sha256Hash': string;
    'analysisId': number;
    'similarity'?: number | null;
    'confidence'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "functionId",
            "baseName": "function_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "binaryId",
            "baseName": "binary_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "functionName",
            "baseName": "function_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "functionVaddr",
            "baseName": "function_vaddr",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "mangledName",
            "baseName": "mangled_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "debug",
            "baseName": "debug",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "binaryName",
            "baseName": "binary_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "sha256Hash",
            "baseName": "sha_256_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "analysisId",
            "baseName": "analysis_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "similarity",
            "baseName": "similarity",
            "type": "number",
            "format": ""
        },
        {
            "name": "confidence",
            "baseName": "confidence",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MatchedFunction.attributeTypeMap;
    }

    public constructor() {
    }
}
