/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MatchedFunctionSuggestion {
    /**
    * Unique identifier of the matched function
    */
    'functionId': number;
    /**
    * Virtual address of the matched function
    */
    'functionVaddr': number;
    'suggestedName'?: string | null;
    /**
    * De-mangled name of the function group that contains the matched functions
    */
    'suggestedDemangledName': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "functionId",
            "baseName": "function_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "functionVaddr",
            "baseName": "function_vaddr",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "suggestedName",
            "baseName": "suggested_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "suggestedDemangledName",
            "baseName": "suggested_demangled_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MatchedFunctionSuggestion.attributeTypeMap;
    }

    public constructor() {
    }
}
