/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PaginationModel } from '../models/PaginationModel';
import { HttpFile } from '../http/http';

export class MetaModel {
    'pagination'?: PaginationModel | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pagination",
            "baseName": "pagination",
            "type": "PaginationModel",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MetaModel.attributeTypeMap;
    }

    public constructor() {
    }
}
