/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MITRETechnique {
    /**
    * Starting address of the technique
    */
    'startAddr': string;
    /**
    * Ending address of the technique
    */
    'endAddr': string;
    /**
    * Function address where the technique is found
    */
    'functionAddr': string;
    /**
    * MITRE technique identifier
    */
    'techniqueId': string;
    /**
    * Name of the MITRE technique
    */
    'techniqueName': string;
    /**
    * Description of the technique
    */
    'description': string;
    /**
    * Unique identifier of the function containing the technique
    */
    'functionId': number;
    /**
    * Name of the function containing the technique
    */
    'functionName': string;
    /**
    * URL to the MITRE ATT&CK technique page
    */
    'techniqueUrl': string;
    /**
    * Full description of the MITRE technique from ATT&CK
    */
    'techniqueDescription': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "startAddr",
            "baseName": "start_addr",
            "type": "string",
            "format": ""
        },
        {
            "name": "endAddr",
            "baseName": "end_addr",
            "type": "string",
            "format": ""
        },
        {
            "name": "functionAddr",
            "baseName": "function_addr",
            "type": "string",
            "format": ""
        },
        {
            "name": "techniqueId",
            "baseName": "technique_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "techniqueName",
            "baseName": "technique_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "functionId",
            "baseName": "function_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "functionName",
            "baseName": "function_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "techniqueUrl",
            "baseName": "technique_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "techniqueDescription",
            "baseName": "technique_description",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MITRETechnique.attributeTypeMap;
    }

    public constructor() {
    }
}
