/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Custom enum for the model name
*/
export enum ModelName {
    Binnet05X86Windows = 'binnet-0.5-x86-windows',
    Binnet05X86Linux = 'binnet-0.5-x86-linux',
    Binnet05X86Macos = 'binnet-0.5-x86-macos',
    Binnet05X86Android = 'binnet-0.5-x86-android',
    Binnet05X8632Windows = 'binnet-0.5-x86-32-windows',
    Binnet05X8632Linux = 'binnet-0.5-x86-32-linux',
    Binnet05Arm64Windows = 'binnet-0.5-arm-64-windows',
    Binnet05Arm64Linux = 'binnet-0.5-arm-64-linux'
}
