/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class NameConfidence {
    /**
    * The suggested function name
    */
    'name': string;
    /**
    * Confidence score as a percentage
    */
    'confidence': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "confidence",
            "baseName": "confidence",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NameConfidence.attributeTypeMap;
    }

    public constructor() {
    }
}
