/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class NameSourceType {
    /**
    * The source (process) the function name came from
    */
    'type': NameSourceTypeTypeEnum;
    'functionId'?: number | null;
    'binaryId'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "NameSourceTypeTypeEnum",
            "format": ""
        },
        {
            "name": "functionId",
            "baseName": "function_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "binaryId",
            "baseName": "binary_id",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NameSourceType.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum NameSourceTypeTypeEnum {
    System = 'SYSTEM',
    User = 'USER',
    AutoUnstrip = 'AUTO_UNSTRIP',
    External = 'EXTERNAL',
    AiUnstrip = 'AI_UNSTRIP'
}

