/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class NetworkOverviewMetadata {
    'host': string;
    'countryCode': string;
    'ASN': string;
    'type': NetworkOverviewMetadataTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "host",
            "baseName": "host",
            "type": "string",
            "format": ""
        },
        {
            "name": "countryCode",
            "baseName": "country_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "ASN",
            "baseName": "ASN",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "NetworkOverviewMetadataTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NetworkOverviewMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum NetworkOverviewMetadataTypeEnum {
    Metadata = 'metadata'
}

