/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NetworkOverviewDnsAnswer } from '../models/NetworkOverviewDnsAnswer';
import { HttpFile } from '../http/http';

export class NetworkOverviewDns {
    'host': string;
    'type': string;
    'answers': Array<NetworkOverviewDnsAnswer>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "host",
            "baseName": "host",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "answers",
            "baseName": "answers",
            "type": "Array<NetworkOverviewDnsAnswer>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NetworkOverviewDns.attributeTypeMap;
    }

    public constructor() {
    }
}
