/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class OrganisationGroup {
    'createdAt': Date;
    'name': string | null;
    'organisationGroupId': number;
    'organisationId': number;
    'teamId': number;
    'updatedAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "organisationGroupId",
            "baseName": "organisation_group_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "organisationId",
            "baseName": "organisation_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "teamId",
            "baseName": "team_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return OrganisationGroup.attributeTypeMap;
    }

    public constructor() {
    }
}
