/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum Origin {
    RevEngMalware = 'RevEng-Malware',
    RevEngLibrary = 'RevEng-Library',
    RevEngBenign = 'RevEng-Benign',
    RevEng = 'RevEng',
    RevEngHeuristic = 'RevEng-Heuristic',
    RevEngUnknown = 'RevEng-Unknown',
    VirusTotal = 'VirusTotal',
    MalwareBazaar = 'MalwareBazaar'
}
