/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SinglePDBEntryModel } from '../models/SinglePDBEntryModel';
import { HttpFile } from '../http/http';

export class PDBDebugModel {
    'debugEntries': Array<SinglePDBEntryModel>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "debugEntries",
            "baseName": "debug_entries",
            "type": "Array<SinglePDBEntryModel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PDBDebugModel.attributeTypeMap;
    }

    public constructor() {
    }
}
