/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StageStatus } from '../models/StageStatus';
import { HttpFile } from '../http/http';

export class PipelineStatusResponse {
    'stages': Array<StageStatus>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "stages",
            "baseName": "stages",
            "type": "Array<StageStatus>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PipelineStatusResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
