/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PriceSummary {
    /**
    * Lowercase ISO 4217 currency code.
    */
    'currency': string;
    /**
    * Billing interval at which the price recurs.
    */
    'interval': PriceSummaryIntervalEnum;
    /**
    * Price per billing interval, in the smallest unit of the currency.
    */
    'unitAmount': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "PriceSummaryIntervalEnum",
            "format": ""
        },
        {
            "name": "unitAmount",
            "baseName": "unit_amount",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return PriceSummary.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum PriceSummaryIntervalEnum {
    Month = 'month',
    Year = 'year',
    UnknownDefaultOpenApi = '11184809'
}

