/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReportEvent } from '../models/ReportEvent';
import { HttpFile } from '../http/http';

export class ProcessActivityEntry {
    'args'?: Array<string> | null;
    'childSeqid': number;
    'events'?: Array<ReportEvent> | null;
    'exitCode'?: number;
    'exitCodeStr'?: string;
    'name': string;
    'pid': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "args",
            "baseName": "args",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "childSeqid",
            "baseName": "child_seqid",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<ReportEvent>",
            "format": ""
        },
        {
            "name": "exitCode",
            "baseName": "exit_code",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "exitCodeStr",
            "baseName": "exit_code_str",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "pid",
            "baseName": "pid",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ProcessActivityEntry.attributeTypeMap;
    }

    public constructor() {
    }
}
