/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProcessDump } from '../models/ProcessDump';
import { HttpFile } from '../http/http';

export class ProcessDumpsData {
    'count': number;
    'dumps': Array<ProcessDump>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": ""
        },
        {
            "name": "dumps",
            "baseName": "dumps",
            "type": "Array<ProcessDump>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProcessDumpsData.attributeTypeMap;
    }

    public constructor() {
    }
}
