/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProgressMessage {
    /**
    * Severity level
    */
    'level': ProgressMessageLevelEnum;
    /**
    * Step name when the message was emitted
    */
    'step': string;
    /**
    * Message text
    */
    'text': string;
    /**
    * When the message was emitted
    */
    'timestamp': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "level",
            "baseName": "level",
            "type": "ProgressMessageLevelEnum",
            "format": ""
        },
        {
            "name": "step",
            "baseName": "step",
            "type": "string",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return ProgressMessage.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ProgressMessageLevelEnum {
    Info = 'INFO',
    Warn = 'WARN',
    Error = 'ERROR'
}

