/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AnalysisStringInput } from '../models/AnalysisStringInput';
import { HttpFile } from '../http/http';

export class PutAnalysisStringsRequest {
    /**
    * The strings to add to the analysis
    */
    'strings': Array<AnalysisStringInput>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "strings",
            "baseName": "strings",
            "type": "Array<AnalysisStringInput>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PutAnalysisStringsRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
