/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AnalysisRecord } from '../models/AnalysisRecord';
import { HttpFile } from '../http/http';

export class Recent {
    /**
    * 2D List containing the results of the analysis
    */
    'results': Array<AnalysisRecord>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<AnalysisRecord>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Recent.attributeTypeMap;
    }

    public constructor() {
    }
}
