/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RenameUnnamedFunctionsResult {
    /**
    * Analysis the run was performed against
    */
    'analysisId': number;
    /**
    * Functions whose rename attempt errored
    */
    'failed': number;
    /**
    * Functions successfully renamed
    */
    'renamed': number;
    /**
    * Functions the agent chose not to rename
    */
    'skipped': number;
    /**
    * Unnamed functions the run considered
    */
    'total': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "analysisId",
            "baseName": "analysis_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "failed",
            "baseName": "failed",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "renamed",
            "baseName": "renamed",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "skipped",
            "baseName": "skipped",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return RenameUnnamedFunctionsResult.attributeTypeMap;
    }

    public constructor() {
    }
}
