/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IOC } from '../models/IOC';
import { MITRETechnique } from '../models/MITRETechnique';
import { HttpFile } from '../http/http';

export class ReportAnalysisResponse {
    /**
    * A markdown summary of the report
    */
    'summary': string;
    /**
    * The type of software being analyzed
    */
    'softwareType': ReportAnalysisResponseSoftwareTypeEnum;
    /**
    * The total number of functions identified in the binary
    */
    'totalNumberOfFunctions': number;
    /**
    * The number of functions that were analyzed in the binary
    */
    'numberOfAnalysedFunctions': number;
    /**
    * A summary in markdown format of the attack flow
    */
    'attackFlowSummary': string;
    /**
    * A list of IOCs (Indicators of Compromise) found in the analysis
    */
    'iOCs': Array<IOC>;
    /**
    * A series of MITRE Techniques found
    */
    'executableTechniques': Array<MITRETechnique>;
    /**
    * The YARA rule generated for the binary
    */
    'yaraRule': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "softwareType",
            "baseName": "software_type",
            "type": "ReportAnalysisResponseSoftwareTypeEnum",
            "format": ""
        },
        {
            "name": "totalNumberOfFunctions",
            "baseName": "total_number_of_functions",
            "type": "number",
            "format": ""
        },
        {
            "name": "numberOfAnalysedFunctions",
            "baseName": "number_of_analysed_functions",
            "type": "number",
            "format": ""
        },
        {
            "name": "attackFlowSummary",
            "baseName": "attack_flow_summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "iOCs",
            "baseName": "IOCs",
            "type": "Array<IOC>",
            "format": ""
        },
        {
            "name": "executableTechniques",
            "baseName": "executable_techniques",
            "type": "Array<MITRETechnique>",
            "format": ""
        },
        {
            "name": "yaraRule",
            "baseName": "yara_rule",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReportAnalysisResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ReportAnalysisResponseSoftwareTypeEnum {
    Malicious = 'Malicious',
    Benign = 'Benign',
    PotentiallyUnwantedApplicationPua = 'Potentially Unwanted Application (PUA)',
    Legitimate = 'Legitimate',
    BackdooredLegitimateSoftware = 'Backdoored Legitimate Software'
}

