/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DrakvufFileMetadata } from '../models/DrakvufFileMetadata';
import { ReportOptions } from '../models/ReportOptions';
import { HttpFile } from '../http/http';

export class ReportInfo {
    'file'?: DrakvufFileMetadata;
    'id': string | null;
    'options'?: ReportOptions;
    'osProfile'?: string | null;
    'status'?: string | null;
    'timeAnalysisFinished'?: string | null;
    'timeExecutionStarted'?: string | null;
    'timeStarted'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "file",
            "baseName": "file",
            "type": "DrakvufFileMetadata",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "ReportOptions",
            "format": ""
        },
        {
            "name": "osProfile",
            "baseName": "os_profile",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeAnalysisFinished",
            "baseName": "time_analysis_finished",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeExecutionStarted",
            "baseName": "time_execution_started",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeStarted",
            "baseName": "time_started",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReportInfo.attributeTypeMap;
    }

    public constructor() {
    }
}
