/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ReportOptions {
    'archiveEntryPath'?: string | null;
    'extractArchive'?: boolean;
    'guestTargetDirectory'?: string | null;
    'guestWorkingDirectory'?: string | null;
    'netEnable'?: boolean;
    'osProfile'?: string | null;
    'plugins'?: Array<string> | null;
    'preset'?: string | null;
    'sampleFilename'?: string | null;
    'startCommand'?: string | null;
    'startMethod'?: string | null;
    'timeout'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "archiveEntryPath",
            "baseName": "archive_entry_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "extractArchive",
            "baseName": "extract_archive",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "guestTargetDirectory",
            "baseName": "guest_target_directory",
            "type": "string",
            "format": ""
        },
        {
            "name": "guestWorkingDirectory",
            "baseName": "guest_working_directory",
            "type": "string",
            "format": ""
        },
        {
            "name": "netEnable",
            "baseName": "net_enable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "osProfile",
            "baseName": "os_profile",
            "type": "string",
            "format": ""
        },
        {
            "name": "plugins",
            "baseName": "plugins",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "preset",
            "baseName": "preset",
            "type": "string",
            "format": ""
        },
        {
            "name": "sampleFilename",
            "baseName": "sample_filename",
            "type": "string",
            "format": ""
        },
        {
            "name": "startCommand",
            "baseName": "start_command",
            "type": "string",
            "format": ""
        },
        {
            "name": "startMethod",
            "baseName": "start_method",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeout",
            "baseName": "timeout",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ReportOptions.attributeTypeMap;
    }

    public constructor() {
    }
}
