/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ExtractedBinary } from '../models/ExtractedBinary';
import { ExtractionFailure } from '../models/ExtractionFailure';
import { HttpFile } from '../http/http';

export class ResultBody {
    /**
    * Child binaries recovered from the extraction.
    */
    'binaries': Array<ExtractedBinary> | null;
    /**
    * Number of nested-archive extraction passes taken.
    */
    'extractionDepth': number;
    /**
    * Per-file extraction failures, keyed by filename.
    */
    'filenameToFailure': { [key: string]: ExtractionFailure; };
    /**
    * Files skipped because they were not recognised as binaries.
    */
    'skippedFiles': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "binaries",
            "baseName": "binaries",
            "type": "Array<ExtractedBinary>",
            "format": ""
        },
        {
            "name": "extractionDepth",
            "baseName": "extraction_depth",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "filenameToFailure",
            "baseName": "filename_to_failure",
            "type": "{ [key: string]: ExtractionFailure; }",
            "format": ""
        },
        {
            "name": "skippedFiles",
            "baseName": "skipped_files",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ResultBody.attributeTypeMap;
    }

    public constructor() {
    }
}
