/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SandboxStartMethod } from '../models/SandboxStartMethod';
import { SandboxTimeout } from '../models/SandboxTimeout';
import { HttpFile } from '../http/http';

export class SandboxOptions {
    'enabled'?: boolean;
    /**
    * The command line parameters to pass to the dynamic execution sandbox. Requires `sandbox` to be True.
    */
    'commandLineArgs'?: string;
    'startMethod'?: SandboxStartMethod | null;
    /**
    * Maximum execution time for the sandbox run, in seconds. Allowed values: 120 (2m), 180 (3m), 300 (5m), 600 (10m).
    */
    'timeout'?: SandboxTimeout;
    'archiveSha256Hash'?: string | null;
    'archiveEntryPath'?: string | null;
    'archivePassword'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "commandLineArgs",
            "baseName": "command_line_args",
            "type": "string",
            "format": ""
        },
        {
            "name": "startMethod",
            "baseName": "start_method",
            "type": "SandboxStartMethod",
            "format": ""
        },
        {
            "name": "timeout",
            "baseName": "timeout",
            "type": "SandboxTimeout",
            "format": ""
        },
        {
            "name": "archiveSha256Hash",
            "baseName": "archive_sha_256_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "archiveEntryPath",
            "baseName": "archive_entry_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "archivePassword",
            "baseName": "archive_password",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SandboxOptions.attributeTypeMap;
    }

    public constructor() {
    }
}


