/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReportEvent } from '../models/ReportEvent';
import { HttpFile } from '../http/http';

export class ScheduledTaskEntry {
    'command'?: string;
    'day'?: string;
    'endDate'?: string;
    'events'?: Array<ReportEvent> | null;
    'executable'?: string;
    'modifier'?: string;
    'runAs'?: string;
    'scheduleType'?: string;
    'startDate'?: string;
    'startTime'?: string;
    'taskName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "command",
            "baseName": "command",
            "type": "string",
            "format": ""
        },
        {
            "name": "day",
            "baseName": "day",
            "type": "string",
            "format": ""
        },
        {
            "name": "endDate",
            "baseName": "end_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<ReportEvent>",
            "format": ""
        },
        {
            "name": "executable",
            "baseName": "executable",
            "type": "string",
            "format": ""
        },
        {
            "name": "modifier",
            "baseName": "modifier",
            "type": "string",
            "format": ""
        },
        {
            "name": "runAs",
            "baseName": "run_as",
            "type": "string",
            "format": ""
        },
        {
            "name": "scheduleType",
            "baseName": "schedule_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskName",
            "baseName": "task_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ScheduledTaskEntry.attributeTypeMap;
    }

    public constructor() {
    }
}
