/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SingleSectionModel } from '../models/SingleSectionModel';
import { HttpFile } from '../http/http';

export class SectionModel {
    'numberOfSections': number;
    'sections': Array<SingleSectionModel>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "numberOfSections",
            "baseName": "number_of_sections",
            "type": "number",
            "format": ""
        },
        {
            "name": "sections",
            "baseName": "sections",
            "type": "Array<SingleSectionModel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SectionModel.attributeTypeMap;
    }

    public constructor() {
    }
}
