/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SecurityFinding } from '../models/SecurityFinding';
import { HttpFile } from '../http/http';

export class SecurityScanResult {
    /**
    * Analysis the run was performed against
    */
    'analysisId': number;
    /**
    * Whether the run was cancelled before it covered every function
    */
    'cancelled': boolean;
    /**
    * Functions successfully decompiled and scanned
    */
    'decompiled': number;
    /**
    * Functions whose decompilation or scan attempt errored
    */
    'failed': number;
    /**
    * Shaped semgrep findings, one per result
    */
    'securityScan'?: Array<SecurityFinding> | null;
    /**
    * Functions the run considered
    */
    'total': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "analysisId",
            "baseName": "analysis_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "cancelled",
            "baseName": "cancelled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "decompiled",
            "baseName": "decompiled",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "failed",
            "baseName": "failed",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "securityScan",
            "baseName": "security_scan",
            "type": "Array<SecurityFinding>",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return SecurityScanResult.attributeTypeMap;
    }

    public constructor() {
    }
}
