/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SecurityFinding {
    /**
    * Semgrep rule ID that matched
    */
    'checkId'?: string;
    /**
    * Semgrep\'s confidence in the finding
    */
    'confidence'?: SecurityFindingConfidenceEnum;
    /**
    * CWE identifiers associated with the finding
    */
    'cwe'?: Array<string> | null;
    /**
    * Line the finding ends on
    */
    'endLine'?: number;
    /**
    * ID of the function the finding was reported in
    */
    'functionId'?: number;
    /**
    * Name of the function the finding was reported in
    */
    'functionName'?: string;
    /**
    * Estimated impact of the finding
    */
    'impact'?: SecurityFindingImpactEnum;
    /**
    * Human-readable description of the finding
    */
    'message'?: string;
    /**
    * Severity of the finding
    */
    'severity'?: SecurityFindingSeverityEnum;
    /**
    * Source lines making up the reported snippet
    */
    'snippetLines'?: Array<string> | null;
    /**
    * Line the reported snippet starts on
    */
    'snippetStartLine'?: number;
    /**
    * Line the finding starts on
    */
    'startLine'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "checkId",
            "baseName": "check_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "confidence",
            "baseName": "confidence",
            "type": "SecurityFindingConfidenceEnum",
            "format": ""
        },
        {
            "name": "cwe",
            "baseName": "cwe",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "endLine",
            "baseName": "end_line",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "functionId",
            "baseName": "function_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "functionName",
            "baseName": "function_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "impact",
            "baseName": "impact",
            "type": "SecurityFindingImpactEnum",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "severity",
            "baseName": "severity",
            "type": "SecurityFindingSeverityEnum",
            "format": ""
        },
        {
            "name": "snippetLines",
            "baseName": "snippet_lines",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "snippetStartLine",
            "baseName": "snippet_start_line",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "startLine",
            "baseName": "start_line",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return SecurityFinding.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SecurityFindingConfidenceEnum {
    Low = 'LOW',
    Medium = 'MEDIUM',
    High = 'HIGH',
    UnknownDefaultOpenApi = '11184809'
}
export enum SecurityFindingImpactEnum {
    Low = 'LOW',
    Medium = 'MEDIUM',
    High = 'HIGH',
    UnknownDefaultOpenApi = '11184809'
}
export enum SecurityFindingSeverityEnum {
    Low = 'LOW',
    Medium = 'MEDIUM',
    High = 'HIGH',
    Critical = 'CRITICAL',
    UnknownDefaultOpenApi = '11184809'
}

