/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SecurityChecksResult } from '../models/SecurityChecksResult';
import { HttpFile } from '../http/http';

export class SecurityChecksResponse {
    'binaryId': number;
    'totalResults': number;
    'results': Array<SecurityChecksResult>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "binaryId",
            "baseName": "binary_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalResults",
            "baseName": "total_results",
            "type": "number",
            "format": ""
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<SecurityChecksResult>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SecurityChecksResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
