/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConfidenceType } from '../models/ConfidenceType';
import { SeverityType } from '../models/SeverityType';
import { VulnerabilityType } from '../models/VulnerabilityType';
import { HttpFile } from '../http/http';

export class SecurityChecksResult {
    'functionId': number;
    'functionName': string;
    'name': string;
    'vulnClass': VulnerabilityType;
    'description': string;
    'remediation': string;
    'confidence': ConfidenceType;
    'severity': SeverityType;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "functionId",
            "baseName": "function_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "functionName",
            "baseName": "function_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "vulnClass",
            "baseName": "vuln_class",
            "type": "VulnerabilityType",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "remediation",
            "baseName": "remediation",
            "type": "string",
            "format": ""
        },
        {
            "name": "confidence",
            "baseName": "confidence",
            "type": "ConfidenceType",
            "format": ""
        },
        {
            "name": "severity",
            "baseName": "severity",
            "type": "SeverityType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SecurityChecksResult.attributeTypeMap;
    }

    public constructor() {
    }
}


