/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Represents the information about a segment.  This is the per-xref view, carried on :class:`XRef.segment`. The binary-wide ``AnalysisModel.segments`` list is written by a different producer with a different shape -- see :class:`MemorySegment`.  Attributes:     name: The name of the segment.     r: Determines if the segment has read permission.     w: Determines if the segment has write permission.     x: Determines if the segment has execute permission.     start: The start address of the segment.     end: The end address of the segment (inclusive).     kind: Coarse classification of the segment: \"code\", \"data\", or \"other\".
*/
export class SegmentInfo {
    'name'?: string;
    'r'?: boolean | null;
    'w'?: boolean | null;
    'x'?: boolean | null;
    'start'?: number;
    'end'?: number;
    'kind'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "r",
            "baseName": "r",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "w",
            "baseName": "w",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "x",
            "baseName": "x",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "number",
            "format": ""
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "number",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SegmentInfo.attributeTypeMap;
    }

    public constructor() {
    }
}
