/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SignatureStorageEntry } from '../models/SignatureStorageEntry';
import { HttpFile } from '../http/http';

export class SignatureParameterEntry {
    /**
    * Width in bits, when the parameter occupies less than its type\'s full size.
    */
    'bitLength'?: number;
    /**
    * The parameter\'s type, resolvable against the analysis data types list. Absent when the type could not be resolved.
    */
    'dataTypeId'?: number;
    /**
    * Parameter name, absent when the producer had none.
    */
    'name'?: string;
    /**
    * Zero-based argument position.
    */
    'ordinal': number;
    /**
    * Where the parameter is passed.
    */
    'storage'?: SignatureStorageEntry;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bitLength",
            "baseName": "bit_length",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "dataTypeId",
            "baseName": "data_type_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "ordinal",
            "baseName": "ordinal",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "storage",
            "baseName": "storage",
            "type": "SignatureStorageEntry",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SignatureParameterEntry.attributeTypeMap;
    }

    public constructor() {
    }
}
