/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SimilarFunctionsResponse {
    'functionId': number;
    'functionName': string;
    'binaryId': number;
    'binaryName': string;
    'distance': number;
    'embedding3d': Array<number>;
    'embedding1d': Array<number>;
    'sha256Hash': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "functionId",
            "baseName": "function_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "functionName",
            "baseName": "function_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "binaryId",
            "baseName": "binary_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "binaryName",
            "baseName": "binary_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "distance",
            "baseName": "distance",
            "type": "number",
            "format": ""
        },
        {
            "name": "embedding3d",
            "baseName": "embedding_3d",
            "type": "Array<number>",
            "format": ""
        },
        {
            "name": "embedding1d",
            "baseName": "embedding_1d",
            "type": "Array<number>",
            "format": ""
        },
        {
            "name": "sha256Hash",
            "baseName": "sha_256_hash",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SimilarFunctionsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
