/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SingleCodeCertificateModel } from '../models/SingleCodeCertificateModel';
import { HttpFile } from '../http/http';

export class SingleCodeSignatureModel {
    'authenticodeDigest': string;
    'certificates': Array<SingleCodeCertificateModel>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "authenticodeDigest",
            "baseName": "authenticode_digest",
            "type": "string",
            "format": ""
        },
        {
            "name": "certificates",
            "baseName": "certificates",
            "type": "Array<SingleCodeCertificateModel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SingleCodeSignatureModel.attributeTypeMap;
    }

    public constructor() {
    }
}
