/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SingleCodeCertificateModel {
    'version': number;
    'issuedOn': string;
    'expiresOn': string;
    'issuerName': string;
    'serialNumber': string;
    'subjectName': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "number",
            "format": ""
        },
        {
            "name": "issuedOn",
            "baseName": "issued_on",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiresOn",
            "baseName": "expires_on",
            "type": "string",
            "format": ""
        },
        {
            "name": "issuerName",
            "baseName": "issuer_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "serialNumber",
            "baseName": "serial_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "subjectName",
            "baseName": "subject_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SingleCodeCertificateModel.attributeTypeMap;
    }

    public constructor() {
    }
}
