/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class StartBatchMatchingInputBody {
    /**
    * Binary IDs to match the analysis against, one workflow per binary.
    */
    'binaryIds': Array<number> | null;
    /**
    * Restrict matches to candidates with these debug source types. Defaults to [\"SYSTEM\"].
    */
    'debugTypes'?: Array<string | null> | null;
    /**
    * Similarity floor as a percentage. Defaults to 90.
    */
    'minSimilarity'?: number;
    /**
    * Max matches returned per source function. Defaults to 1.
    */
    'resultsPerFunction'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "binaryIds",
            "baseName": "binary_ids",
            "type": "Array<number>",
            "format": "int64"
        },
        {
            "name": "debugTypes",
            "baseName": "debug_types",
            "type": "Array<string | null>",
            "format": ""
        },
        {
            "name": "minSimilarity",
            "baseName": "min_similarity",
            "type": "number",
            "format": "double"
        },
        {
            "name": "resultsPerFunction",
            "baseName": "results_per_function",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return StartBatchMatchingInputBody.attributeTypeMap;
    }

    public constructor() {
    }
}
