/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProgressMessage } from '../models/ProgressMessage';
import { HttpFile } from '../http/http';

export class StartMatchingOutputBody {
    /**
    * Opaque token for this matching run. Pass it to the GET/status endpoints\' match_id query parameter to fetch this exact run.
    */
    'matchId': string;
    /**
    * Log messages emitted during execution
    */
    'messages': Array<ProgressMessage> | null;
    /**
    * Current workflow status
    */
    'status': StartMatchingOutputBodyStatusEnum;
    /**
    * Name of the current step
    */
    'step': string;
    /**
    * Zero-based index of the current step
    */
    'stepIndex': number;
    /**
    * Total number of steps in the workflow
    */
    'stepsTotal': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "matchId",
            "baseName": "match_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "messages",
            "baseName": "messages",
            "type": "Array<ProgressMessage>",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "StartMatchingOutputBodyStatusEnum",
            "format": ""
        },
        {
            "name": "step",
            "baseName": "step",
            "type": "string",
            "format": ""
        },
        {
            "name": "stepIndex",
            "baseName": "step_index",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "stepsTotal",
            "baseName": "steps_total",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return StartMatchingOutputBody.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum StartMatchingOutputBodyStatusEnum {
    Uninitialised = 'UNINITIALISED',
    Pending = 'PENDING',
    Running = 'RUNNING',
    Completed = 'COMPLETED',
    Failed = 'FAILED',
    UnknownDefaultOpenApi = '11184809'
}

