/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Custom enum for the analysis status
*/
export enum StatusInput {
    Uploaded = 'Uploaded',
    Queued = 'Queued',
    Complete = 'Complete',
    Error = 'Error',
    Processing = 'Processing',
    All = 'All'
}
