/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Custom enum for the analysis status
*/
export enum StatusInput {
    Uploaded = 'Uploaded',
    Queued = 'Queued',
    Complete = 'Complete',
    Error = 'Error',
    Processing = 'Processing',
    All = 'All'
}
