/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EventAttemptFailed } from '../models/EventAttemptFailed';
import { EventAttemptStarted } from '../models/EventAttemptStarted';
import { EventDebugPrompt } from '../models/EventDebugPrompt';
import { EventDecompFailed } from '../models/EventDecompFailed';
import { EventDecompFinished } from '../models/EventDecompFinished';
import { EventProse } from '../models/EventProse';
import { EventRenameApplied } from '../models/EventRenameApplied';
import { EventSourceDelta } from '../models/EventSourceDelta';
import { EventSourceReset } from '../models/EventSourceReset';
import { EventWarning } from '../models/EventWarning';
import { HttpFile } from '../http/http';

/**
 * @type StreamAiDecompilation200ResponseInner
 * Type
 * @export
 */
export type StreamAiDecompilation200ResponseInner = EventAttemptFailed | EventAttemptStarted | EventDebugPrompt | EventDecompFailed | EventDecompFinished | EventProse | EventRenameApplied | EventSourceDelta | EventSourceReset | EventWarning;

/**
* @type StreamAiDecompilation200ResponseInnerClass
* @export
*/
export class StreamAiDecompilation200ResponseInnerClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}









