/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppApiRestV2FunctionsResponsesFunction } from '../models/AppApiRestV2FunctionsResponsesFunction';
import { HttpFile } from '../http/http';

/**
* This is a string with the functions where the string is used.  A function string is a string literal referenced within a function. When analyzing stripped or obfuscated binaries, function strings can help identify the function’s purpose.
*/
export class StringFunctions {
    /**
    * The value of the string literal
    */
    'value': string;
    /**
    * The function ids the string literal was found within
    */
    'functions': Array<AppApiRestV2FunctionsResponsesFunction>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "functions",
            "baseName": "functions",
            "type": "Array<AppApiRestV2FunctionsResponsesFunction>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StringFunctions.attributeTypeMap;
    }

    public constructor() {
    }
}
