/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppApiRestV2FunctionsResponsesFunction } from '../models/AppApiRestV2FunctionsResponsesFunction';
import { StringSource } from '../models/StringSource';
import { HttpFile } from '../http/http';

/**
* This is a string with the functions where the string is used.  A function string is a string literal referenced within a function. When analyzing stripped or obfuscated binaries, function strings can help identify the function’s purpose.
*/
export class StringFunctions {
    /**
    * The function ids the string literal was found within
    */
    'functions': Array<AppApiRestV2FunctionsResponsesFunction>;
    /**
    * The source of the string
    */
    'source'?: StringSource;
    /**
    * The value of the string literal
    */
    'value': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "functions",
            "baseName": "functions",
            "type": "Array<AppApiRestV2FunctionsResponsesFunction>",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "StringSource",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StringFunctions.attributeTypeMap;
    }

    public constructor() {
    }
}


