/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DataTypeMemberEntry } from '../models/DataTypeMemberEntry';
import { HttpFile } from '../http/http';

export class StructDefinition {
    /**
    * The type\'s fields, in offset order.
    */
    'members': Array<DataTypeMemberEntry> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "members",
            "baseName": "members",
            "type": "Array<DataTypeMemberEntry>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StructDefinition.attributeTypeMap;
    }

    public constructor() {
    }
}
