/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SubmitFeedbackBody {
    /**
    * The route the caller was on when they submitted feedback
    */
    'currentRoute': string;
    /**
    * The feedback text
    */
    'feedback': string;
    /**
    * Optional URL to a screen capture related to the feedback
    */
    'screenCaptureUrl'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "currentRoute",
            "baseName": "current_route",
            "type": "string",
            "format": ""
        },
        {
            "name": "feedback",
            "baseName": "feedback",
            "type": "string",
            "format": ""
        },
        {
            "name": "screenCaptureUrl",
            "baseName": "screen_capture_url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SubmitFeedbackBody.attributeTypeMap;
    }

    public constructor() {
    }
}
