/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SummaryData {
    /**
    * A URL to the JSON Schema for this object.
    */
    'schema'?: string;
    /**
    * Summary with code tags removed
    */
    'aiSummary': string;
    /**
    * Raw summary from the model
    */
    'summary': string;
    /**
    * Task status
    */
    'taskStatus': SummaryDataTaskStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "schema",
            "baseName": "$schema",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "aiSummary",
            "baseName": "ai_summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskStatus",
            "baseName": "task_status",
            "type": "SummaryDataTaskStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SummaryData.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SummaryDataTaskStatusEnum {
    Uninitialised = 'UNINITIALISED',
    Pending = 'PENDING',
    Completed = 'COMPLETED',
    UnknownDefaultOpenApi = '11184809'
}

