/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TimestampModel {
    'peTimestamp': number;
    'exportTimestamp': number;
    'debugTimestamp': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "peTimestamp",
            "baseName": "pe_timestamp",
            "type": "number",
            "format": ""
        },
        {
            "name": "exportTimestamp",
            "baseName": "export_timestamp",
            "type": "number",
            "format": ""
        },
        {
            "name": "debugTimestamp",
            "baseName": "debug_timestamp",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TimestampModel.attributeTypeMap;
    }

    public constructor() {
    }
}
