/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TriageFunction {
    /**
    * Virtual address of the function
    */
    'address': number;
    /**
    * Capability categories the function exhibits
    */
    'capabilities': Array<string> | null;
    /**
    * ID of the function
    */
    'id': number;
    /**
    * Maliciousness score for the function, 0 to 1
    */
    'score': number;
    /**
    * What the function does
    */
    'summary': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "capabilities",
            "baseName": "capabilities",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "score",
            "baseName": "score",
            "type": "number",
            "format": "double"
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TriageFunction.attributeTypeMap;
    }

    public constructor() {
    }
}
