/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TriageFunctionResponse } from '../models/TriageFunctionResponse';
import { HttpFile } from '../http/http';

export class TriageReportResponse {
    /**
    * Overall triage score for the software
    */
    'softwareScore': number;
    /**
    * Summary of the triage analysis
    */
    'summary': string;
    /**
    * List of triaged functions
    */
    'functions': Array<TriageFunctionResponse>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "softwareScore",
            "baseName": "software_score",
            "type": "number",
            "format": ""
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "functions",
            "baseName": "functions",
            "type": "Array<TriageFunctionResponse>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TriageReportResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
