/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TriggerExecutionExplainInputBody {
    /**
    * Execution category to focus the explanation on.
    */
    'category': TriggerExecutionExplainInputBodyCategoryEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "category",
            "baseName": "category",
            "type": "TriggerExecutionExplainInputBodyCategoryEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TriggerExecutionExplainInputBody.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum TriggerExecutionExplainInputBodyCategoryEnum {
    DynamicResolve = 'dynamic-resolve',
    Hooking = 'hooking',
    Injection = 'injection',
    MemoryExec = 'memory-exec',
    ModuleLoad = 'module-load',
    ProcessControl = 'process-control',
    ProcessCreate = 'process-create',
    ScriptExec = 'script-exec',
    Shellcode = 'shellcode',
    ThreadCreate = 'thread-create',
    UnknownDefaultOpenApi = '11184809'
}

