/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TriggerDynamicExecutionInputBody {
    /**
    * Relative path of the entry inside the archive to execute
    */
    'archiveEntryPath'?: string;
    /**
    * Password for an encrypted archive
    */
    'archivePassword'?: string;
    /**
    * SHA-256 of the archive object to send to the sandbox instead of the analysed binary
    */
    'archiveSha256Hash'?: string;
    /**
    * Command-line arguments passed to the sample when the sandbox launches it
    */
    'commandLineArgs'?: string;
    /**
    * How the sandbox launches the sample. Defaults to the sandbox\'s standard behaviour when omitted.
    */
    'startMethod'?: TriggerDynamicExecutionInputBodyStartMethodEnum;
    /**
    * Maximum sandbox execution time in seconds
    */
    'timeout'?: TriggerDynamicExecutionInputBodyTimeoutEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "archiveEntryPath",
            "baseName": "archive_entry_path",
            "type": "string",
            "format": ""
        },
        {
            "name": "archivePassword",
            "baseName": "archive_password",
            "type": "string",
            "format": ""
        },
        {
            "name": "archiveSha256Hash",
            "baseName": "archive_sha_256_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "commandLineArgs",
            "baseName": "command_line_args",
            "type": "string",
            "format": ""
        },
        {
            "name": "startMethod",
            "baseName": "start_method",
            "type": "TriggerDynamicExecutionInputBodyStartMethodEnum",
            "format": ""
        },
        {
            "name": "timeout",
            "baseName": "timeout",
            "type": "TriggerDynamicExecutionInputBodyTimeoutEnum",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return TriggerDynamicExecutionInputBody.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum TriggerDynamicExecutionInputBodyStartMethodEnum {
    StandardUserProcess = 'standard_user_process',
    AdministratorProcess = 'administrator_process',
    UnknownDefaultOpenApi = '11184809'
}
export enum TriggerDynamicExecutionInputBodyTimeoutEnum {
    NUMBER_120 = 120,
    NUMBER_180 = 180,
    NUMBER_300 = 300,
    NUMBER_600 = 600,
    NUMBER_unknown_default_open_api = 11184809
}

