/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TriggerNetworkingScanInputBody {
    /**
    * Restrict findings to these categories. Omit to scan the default remote-communication set.
    */
    'categories'?: Array<TriggerNetworkingScanInputBodyCategoriesEnum> | null;
    /**
    * Only report functions whose own name matches a known networking API; skips the calls-into-networking pass, avoiding a bulk call-graph fetch.
    */
    'directOnly'?: boolean;
    /**
    * Restrict findings to these sources. Omit to scan every source.
    */
    'sources'?: Array<TriggerNetworkingScanInputBodySourcesEnum> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<TriggerNetworkingScanInputBodyCategoriesEnum>",
            "format": ""
        },
        {
            "name": "directOnly",
            "baseName": "direct_only",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sources",
            "baseName": "sources",
            "type": "Array<TriggerNetworkingScanInputBodySourcesEnum>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TriggerNetworkingScanInputBody.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum TriggerNetworkingScanInputBodyCategoriesEnum {
    Accept = 'accept',
    Address = 'address',
    Connect = 'connect',
    Dns = 'dns',
    Http = 'http',
    Netinfo = 'netinfo',
    RawPacket = 'raw-packet',
    Recv = 'recv',
    Send = 'send',
    Socket = 'socket',
    Tls = 'tls',
    Url = 'url',
    UnknownDefaultOpenApi = '11184809'
}
export enum TriggerNetworkingScanInputBodySourcesEnum {
    Boost = 'boost',
    Cpp = 'cpp',
    Curl = 'curl',
    Generic = 'generic',
    Libc = 'libc',
    Pcap = 'pcap',
    Poco = 'poco',
    Qt = 'qt',
    Tls = 'tls',
    Windows = 'windows',
    UnknownDefaultOpenApi = '11184809'
}

