/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TriggerCryptoScanInputBody {
    /**
    * Restrict findings to these categories. Omit to scan every category.
    */
    'categories'?: Array<TriggerCryptoScanInputBodyCategoriesEnum> | null;
    /**
    * Only report functions whose own name matches a known crypto API; skips the calls-into-crypto pass, avoiding a bulk call-graph fetch.
    */
    'directOnly'?: boolean;
    /**
    * Restrict findings to these libraries. Omit to scan every library.
    */
    'libraries'?: Array<TriggerCryptoScanInputBodyLibrariesEnum> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<TriggerCryptoScanInputBodyCategoriesEnum>",
            "format": ""
        },
        {
            "name": "directOnly",
            "baseName": "direct_only",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "libraries",
            "baseName": "libraries",
            "type": "Array<TriggerCryptoScanInputBodyLibrariesEnum>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TriggerCryptoScanInputBody.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum TriggerCryptoScanInputBodyCategoriesEnum {
    Symmetric = 'symmetric',
    Asymmetric = 'asymmetric',
    Hashing = 'hashing',
    Mac = 'mac',
    Kdf = 'kdf',
    Rng = 'rng',
    Generic = 'generic',
    UnknownDefaultOpenApi = '11184809'
}
export enum TriggerCryptoScanInputBodyLibrariesEnum {
    Openssl = 'openssl',
    Mbedtls = 'mbedtls',
    Wolfssl = 'wolfssl',
    Libsodium = 'libsodium',
    Libgcrypt = 'libgcrypt',
    WindowsCryptoApi = 'windows_crypto_api',
    Cryptopp = 'cryptopp',
    CppCrypto = 'cpp-crypto',
    Generic = 'generic',
    UnknownDefaultOpenApi = '11184809'
}

