/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TTPSElement } from '../models/TTPSElement';
import { HttpFile } from '../http/http';

export class TTPSData {
    'score': number;
    'ttps': Array<TTPSElement>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "score",
            "baseName": "score",
            "type": "number",
            "format": ""
        },
        {
            "name": "ttps",
            "baseName": "ttps",
            "type": "Array<TTPSElement>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TTPSData.attributeTypeMap;
    }

    public constructor() {
    }
}
