/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * OpenAPI spec version: v2.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TTPSAttack } from '../models/TTPSAttack';
import { TTPSOccurance } from '../models/TTPSOccurance';
import { HttpFile } from '../http/http';

export class TTPSElement {
    'name': string;
    'attack': Array<TTPSAttack>;
    'occurrences': Array<TTPSOccurance>;
    'score': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "attack",
            "baseName": "attack",
            "type": "Array<TTPSAttack>",
            "format": ""
        },
        {
            "name": "occurrences",
            "baseName": "occurrences",
            "type": "Array<TTPSOccurance>",
            "format": ""
        },
        {
            "name": "score",
            "baseName": "score",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TTPSElement.attributeTypeMap;
    }

    public constructor() {
    }
}
