/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SuggestedTypeView } from '../models/SuggestedTypeView';
import { HttpFile } from '../http/http';

export class TypeSuggestionsData {
    /**
    * Language model that produced the suggestions.
    */
    'model'?: string;
    /**
    * Status of the AI decompilation run that would have produced these suggestions.
    */
    'status': TypeSuggestionsDataStatusEnum;
    /**
    * One entry per suggested type. Empty for a run that produced none, and for a run that predates type suggestion — the two are not distinguished.
    */
    'types': Array<SuggestedTypeView> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "model",
            "baseName": "model",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TypeSuggestionsDataStatusEnum",
            "format": ""
        },
        {
            "name": "types",
            "baseName": "types",
            "type": "Array<SuggestedTypeView>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TypeSuggestionsData.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum TypeSuggestionsDataStatusEnum {
    Uninitialised = 'UNINITIALISED',
    Pending = 'PENDING',
    Running = 'RUNNING',
    Completed = 'COMPLETED',
    Failed = 'FAILED',
    UnknownDefaultOpenApi = '11184809'
}

