/**
 * RevEng.AI API
 * RevEng.AI is Similarity Search Engine for executable binaries
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FunctionInfoInput } from '../models/FunctionInfoInput';
import { HttpFile } from '../http/http';

export class UpdateFunctionDataTypes {
    /**
    * Version of the function data types, used to check this update is not overwriting a newer one
    */
    'dataTypesVersion': number;
    /**
    * Function data types information to update
    */
    'dataTypes': FunctionInfoInput;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dataTypesVersion",
            "baseName": "data_types_version",
            "type": "number",
            "format": ""
        },
        {
            "name": "dataTypes",
            "baseName": "data_types",
            "type": "FunctionInfoInput",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateFunctionDataTypes.attributeTypeMap;
    }

    public constructor() {
    }
}
