/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FunctionTypeDefinition } from '../models/FunctionTypeDefinition';
import { HttpFile } from '../http/http';

export class UpdateFunctionDataType {
    /**
    * The type to replace, as returned by the data types list for this analysis.
    */
    'dataTypeId': number;
    'definition': FunctionTypeDefinition;
    'kind': UpdateFunctionDataTypeKindEnum;
    /**
    * Type name. Unique within the analysis for a given namespace and kind.
    */
    'name': string;
    /**
    * The scope qualifying the type name. Omit for a type of the binary\'s own.
    */
    'namespace'?: string;
    /**
    * Size in bytes. Omit when it is not known.
    */
    'size'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dataTypeId",
            "baseName": "data_type_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "definition",
            "baseName": "definition",
            "type": "FunctionTypeDefinition",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "UpdateFunctionDataTypeKindEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "namespace",
            "baseName": "namespace",
            "type": "string",
            "format": ""
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return UpdateFunctionDataType.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum UpdateFunctionDataTypeKindEnum {
    FunctionDefinition = 'FUNCTION_DEFINITION',
    UnknownDefaultOpenApi = '11184809'
}

