/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpdateAnalysisInputBody {
    /**
    * The analysis\' visibility. Changing to a non-PUBLIC scope requires a subscription tier that supports private analyses
    */
    'analysisScope'?: UpdateAnalysisInputBodyAnalysisScopeEnum;
    /**
    * Renames the analysis\' binary. Empty or whitespace-only is rejected
    */
    'binaryName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "analysisScope",
            "baseName": "analysis_scope",
            "type": "UpdateAnalysisInputBodyAnalysisScopeEnum",
            "format": ""
        },
        {
            "name": "binaryName",
            "baseName": "binary_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateAnalysisInputBody.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum UpdateAnalysisInputBodyAnalysisScopeEnum {
    Public = 'PUBLIC',
    Private = 'PRIVATE',
    Team = 'TEAM',
    UnknownDefaultOpenApi = '11184809'
}

