/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V2MatchedFunction } from '../models/V2MatchedFunction';
import { V2NameConfidence } from '../models/V2NameConfidence';
import { HttpFile } from '../http/http';

export class V2FunctionMatch {
    /**
    * Unique identifier of the function
    */
    'functionId': number;
    'matchedFunctions': Array<V2MatchedFunction>;
    'confidences'?: Array<V2NameConfidence> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "functionId",
            "baseName": "function_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "matchedFunctions",
            "baseName": "matched_functions",
            "type": "Array<V2MatchedFunction>",
            "format": ""
        },
        {
            "name": "confidences",
            "baseName": "confidences",
            "type": "Array<V2NameConfidence>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V2FunctionMatch.attributeTypeMap;
    }

    public constructor() {
    }
}
