/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V2FunctionInfoFuncDepsInner } from '../models/V2FunctionInfoFuncDepsInner';
import { V2FunctionType } from '../models/V2FunctionType';
import { HttpFile } from '../http/http';

export class V2FunctionInfo {
    'funcTypes'?: V2FunctionType | null;
    /**
    * List of function dependencies
    */
    'funcDeps': Array<V2FunctionInfoFuncDepsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "funcTypes",
            "baseName": "func_types",
            "type": "V2FunctionType",
            "format": ""
        },
        {
            "name": "funcDeps",
            "baseName": "func_deps",
            "type": "Array<V2FunctionInfoFuncDepsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V2FunctionInfo.attributeTypeMap;
    }

    public constructor() {
    }
}
