/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class VirusTotalScanMetadata {
    /**
    * Lookup status. UNINITIALISED means this binary has never had a lookup triggered.
    */
    'status': VirusTotalScanMetadataStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "VirusTotalScanMetadataStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VirusTotalScanMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum VirusTotalScanMetadataStatusEnum {
    Uninitialised = 'UNINITIALISED',
    Pending = 'PENDING',
    Running = 'RUNNING',
    Completed = 'COMPLETED',
    Failed = 'FAILED',
    UnknownDefaultOpenApi = '11184809'
}

