/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AnalyseCapabilitiesBody } from '../models/AnalyseCapabilitiesBody';
import { ReportAnalysisBody } from '../models/ReportAnalysisBody';
import { HttpFile } from '../http/http';

export class WorkflowDayBody {
    /**
    * ANALYSE_CAPABILITIES agent-task stats for the day
    */
    'analyseCapabilities': AnalyseCapabilitiesBody;
    /**
    * Day this entry covers
    */
    'date': string;
    /**
    * REPORT_ANALYSIS agent-task stats for the day
    */
    'reportAnalysis': ReportAnalysisBody;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "analyseCapabilities",
            "baseName": "analyse_capabilities",
            "type": "AnalyseCapabilitiesBody",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string",
            "format": ""
        },
        {
            "name": "reportAnalysis",
            "baseName": "report_analysis",
            "type": "ReportAnalysisBody",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WorkflowDayBody.attributeTypeMap;
    }

    public constructor() {
    }
}
