/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SegmentInfo } from '../models/SegmentInfo';
import { HttpFile } from '../http/http';

export class XrefToResponse {
    'value': string | null;
    'isScalar'?: boolean | null;
    'isCall'?: boolean | null;
    'isData'?: boolean | null;
    'isString'?: boolean | null;
    'rawData'?: string | null;
    'segment'?: SegmentInfo | null;
    'origStrEncoding'?: string | null;
    'xrefFrom': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "isScalar",
            "baseName": "is_scalar",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isCall",
            "baseName": "is_call",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isData",
            "baseName": "is_data",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isString",
            "baseName": "is_string",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "rawData",
            "baseName": "raw_data",
            "type": "string",
            "format": ""
        },
        {
            "name": "segment",
            "baseName": "segment",
            "type": "SegmentInfo",
            "format": ""
        },
        {
            "name": "origStrEncoding",
            "baseName": "orig_str_encoding",
            "type": "string",
            "format": ""
        },
        {
            "name": "xrefFrom",
            "baseName": "xref_from",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return XrefToResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
