/**
 * RevEng.AI API
 * RevEng.AI is an AI-powered binary analysis platform for reverse engineering and malware analysis. It provides similarity search across executable binaries and functions, AI-driven decompilation, dynamic execution analysis, firmware unpacking, and integration with external threat intelligence sources like VirusTotal.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { XrefFromResponse } from '../models/XrefFromResponse';
import { XrefToResponse } from '../models/XrefToResponse';
import { HttpFile } from '../http/http';

export class XrefResponse {
    'xrefFromList': Array<XrefFromResponse>;
    'xrefToList': Array<XrefToResponse>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "xrefFromList",
            "baseName": "xref_from_list",
            "type": "Array<XrefFromResponse>",
            "format": ""
        },
        {
            "name": "xrefToList",
            "baseName": "xref_to_list",
            "type": "Array<XrefToResponse>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return XrefResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
